/*
 * Cross-check that static/alghash.js (the browser field hash) equals execnode/stark/alghash.py byte-for-byte,
 * so field-hash notes made in the wallet match the exec node + the zk-STARK (doc/privacy.md). Reference values
 * are generated by the Python module. Run: node tests/alghash_js_crosscheck.mjs
 */
import { blake2b, bytesToHex } from "../static/vendor/nado-crypto.js";
import * as A from "../static/alghash.js";

function canon(d) {
  const t = typeof d;
  if (t === "bigint") return d.toString();
  if (t === "number") return String(d);
  if (t === "string") return JSON.stringify(d);
  if (Array.isArray(d)) return "[" + d.map(canon).join(",") + "]";
  throw new Error("bad type " + t);
}
const enc = new TextEncoder();
const blake2bHash = (data, size = 32) => bytesToHex(blake2b(enc.encode(canon(data)), { dkLen: size }));
A.initAlghash(blake2bHash);

let fails = 0;
const eq = (n, got, want) => { const ok = got === want; if (!ok) fails++; console.log(`${ok ? "PASS" : "FAIL"}  ${n}${ok ? "" : `\n   got  ${got}\n   want ${want}`}`); };

const p = A.permute([123n, 456n]);
eq("permute[0]", p[0], 4315221267995540352n);
eq("permute[1]", p[1], 805932795842471149n);
eq("hashn([1,2,3])", A.hashn([1, 2, 3]), 38947860171815534n);
eq("commit(500,0xBEEF,0x1234)", A.commit(500, 0xBEEFn, 0x1234n), 5419927746975474554n);
eq("nullifier(0xCAFE,0x9999)", A.nullifier(0xCAFEn, 0x9999n), 11665953938006595251n);
eq("owner_of(0xCAFE)", A.ownerOf(0xCAFEn), 16555562624311152863n);
eq("merkle_node(111,222)", A.merkleNode(111, 222), 12883855126046763304n);

console.log(`\n${fails ? fails + " FAILED — JS and Python DIVERGE" : "ALL PASSED — JS field hash ≡ Python byte-for-byte"}`);
process.exit(fails ? 1 : 0);
