"""
Autogame — the Python REFERENCE implementation of the march step function (spec: doc/autogame.md).

This is not the game. `execnode/games/autogame.py` (zkasm) is authoritative; this module is the readable
statement of what that assembly is supposed to compute, and the differential oracle the contract test runs
against. `static/autogame-engine.js` is the third implementation. All three must agree step for step — a
disagreement is a bug in the other two until proven otherwise (doc/autogame.md §8).

LINEAGE. The clock is Autogame's (Bismuth, 2017): one step per block, world generated by the miners. The
ECONOMY is MAMEC / "math sword" (PICO-8 v1.70): a fixed turn budget, a risk dial you set yourself, and three
rules that make cowardice unprofitable —

    bloodlust      xp gain scales with how hurt you are (×1 at full, ×3 at death's door)
    renown regen   your score IS your healing (hp += xp // REGEN_DIV), so wealth compounds into survivability
    "easy win"     a fight that didn't hurt you heals you nothing — you must keep escalating

Everything here is integer-only and clamped, mirroring the VM exactly:
  * no subtraction may go negative — the field wraps, and a wrapped `hp` is a 2^64 hit-point pool, so every
    subtraction goes through `c_sub` (the contract does the same with an `lt`+`select` pair);
  * every divisor is < 2^15 (DIVMOD) or < 2^31 with a quotient < 2^32 (DIVMODW), the soundness windows;
  * the two 32-bit hash windows are sliced in exactly the documented order — the contract consumes them in
    the same order with the same divisors, so the bit budget cannot silently drift.
"""

# ── the rules live in the CONTRACT, not here ─────────────────────────────────────────────────────
# execnode/games/autogame.py is the authority; importing its constants is what makes "three
# implementations, cross-checked" honest. If they were restated here, a retune would silently desync the
# oracle from the thing it is meant to be checking, and the differential test would pass while the game
# changed underneath it.
from execnode.games.autogame import (      # noqa: E402
    LEG, MAX_LEGS_PER_CALL, CHAPTER, HP0, STAM_MAX, AGG_MAX, REGEN_DIV, REGEN_CAP_DIV, BOSS_EVERY,
    TIER_EVERY, NIGHT_EVERY, LEVEL_CAP, LIFESTEAL_DIV, HORDE_DIV, STREAK_DIV, DEATH_KEEP, COMPLETE_BONUS,
    POTIONS0, POTION_CAP, POTION_PRICE, HEAL_BASE, SHRINE_BASE, RALLY_BASE, NSLOT, TILE_CUTS, NTILE,
    ROAD, MONSTER, HORDE, ELITE, AMBUSH, MIMIC, HAZARD, SNARE, QUAG, GALE, TOLLGATE, CACHE, BARROW,
    ARMORY, VEIN, GROVE, SHRINE, WELL, CAMP, IDOL, PYRE, FORGE, FORK, RELIC, BOSS,
    A_DEFAULT, A_STRIKE, A_GUARD, A_DODGE, A_POTION, A_SPRINT, A_REST, A_RIGHT, A_RALLY, COST,
    ST_BALANCED, ST_AGGRESSIVE, ST_GUARDED, ST_EVASIVE, STANCES,
    FAM_ATK, FAM_XP, M_SCRAP, M_HIDE, M_ESSENCE, SHARPEN_COST, REINFORCE_COST,
    G_WEAPON, G_HELM, G_BODY, G_SHIELD, G_BOOTS, G_CLOAK, DEF_DIV, RANKS,
    AF_NONE, AF_KEEN, AF_HEAVY, AF_WARD, AF_SWIFT, AF_VAMP, AF_BLAZE, AF_HALLOW, AFFIX_NAMES,
    W_SWORD, W_AXE, W_MAUL, W_SPEAR, NWKIND, WKIND_NAMES,
    KEEN_BONUS, SWIFT_BONUS, JACKPOT_EVERY,
)

FAM_MAT = (M_SCRAP, M_HIDE, M_ESSENCE)   # family -> the material it drops


def c_sub(a, b):
    """Clamped subtraction — the ONLY way this game is allowed to subtract. See doc/autogame.md §8."""
    return a - b if a > b else 0


def rank_of(xp):
    for threshold, name in RANKS:
        if xp < threshold:
            return name
    return "creator"


# ── item packing ─────────────────────────────────────────────────────────────────────────────────
# A gear cell stores 1 + tier*64 + mat*8 + affix, so 0 unambiguously means "empty" (the VM treats a zero
# store as deletion, so 0 must never be a legal item). The slot is implied by WHICH cell holds it.
def pack_item(tier, mat, affix, kind=0):
    # 1 + kind*512 + tier*64 + mat*8 + affix — `kind` is the WEAPON CLASS (0..3), meaningful only in the
    # weapon slot; every other slot rolls 0. 0 still means "empty".
    return 1 + kind * 512 + tier * 64 + mat * 8 + affix


def unpack_item(v):
    if v == 0:
        return (-1, 0, 0, 0)          # (tier, mat, affix, kind)
    v -= 1
    return ((v // 64) % 8, (v // 8) % 8, v % 8, (v // 512) % 4)


def weapon_kind(run):
    """The class of the currently equipped weapon (W_SWORD for a bare-handed run — a neutral baseline)."""
    w = run.gear[G_WEAPON]
    return unpack_item(w)[3] if w else W_SWORD


def has_affix(run, a):
    """Is affix `a` equipped in any slot? The contract caches this in storage and refreshes it on equip;
    deriving it from gear here is the same function, so the two cannot disagree."""
    for g in run.gear:
        if g and unpack_item(g)[2] == a:
            return 1
    return 0


def power(v):
    """An item's single power score: tier dominates, material is the tiebreak."""
    if v == 0:
        return 0
    tier, mat, _affix, _kind = unpack_item(v)
    return tier * 4 + mat


class Run:
    """The full on-chain run record. Field names match the contract's storage map 1:1."""

    def __init__(self, stance=ST_BALANCED, healpct=35, focus=50):
        self.hp = HP0
        self.maxhp = HP0
        self.stam = STAM_MAX
        self.potions = POTIONS0
        self.xp = 0                    # renown earned so far (banked + at risk)
        self.banked = 0                # the portion locked in by a checkpoint — death cannot take it
        self.streak = 0                # consecutive fights since you last healed
        self.depth = 0
        self.kills = 0
        self.stance = stance
        self.healpct = healpct         # standing order: auto-drink below this % of max hp
        self.focus = focus             # MAMEC's slider: 100 = all weapon, 0 = all armour
        self.wlevel = 1                # permanent, crafted
        self.alevel = 1
        self.mats = [0, 0, 0]          # scrap, hide, essence
        self.gear = [0] * NSLOT
        # the aggression dial — the one standing order besides stance/focus/heal. (The per-tile-class
        # doctrine and auto-march died together: manual-only, actions come from commit() per actual tile.)
        self.agg = 1
        self.gale = 0                  # steps of storm left: renown out and damage in both x5/4
        self.pyre = 0                  # steps of lit beacon left: renown out x5/4, no damage rider
        self.alive = 1
        self.done = 0                  # reached step CHAPTER on your feet — the only state that doubles
        self.retired = 0               # walked away voluntarily: you keep everything, but no completion bonus

    def score(self):
        """What actually goes on the board. Everything banked, plus what you can still carry out — all of it
        if you finished or retired on your feet, DEATH_KEEP% if you didn't — and doubled if you walked the
        whole road."""
        risk = c_sub(self.xp, self.banked)
        standing = self.alive or self.done or self.retired
        total = self.banked + (risk if standing else risk * DEATH_KEEP // 100)
        # The road bonus is PRO-RATA on how far you walked, and it is paid only if you are standing. That
        # makes it a live cash-out meter: every step forward raises what retiring is worth, and dying
        # forfeits the whole thing. "One more leg or take the money" is now a real question at every depth,
        # which is the decision the whole design exists to produce.
        if self.done:
            return total + COMPLETE_BONUS
        if self.retired:
            return total + COMPLETE_BONUS * self.depth // CHAPTER
        return total

    def snapshot(self):
        return dict(hp=self.hp, maxhp=self.maxhp, stam=self.stam, potions=self.potions, xp=self.xp,
                    banked=self.banked, streak=self.streak, score=self.score(),
                    depth=self.depth, kills=self.kills, alive=self.alive, done=self.done,
                    wlevel=self.wlevel, alevel=self.alevel, mats=list(self.mats), gear=list(self.gear),
                    pyre=self.pyre)


# ── derived player stats ─────────────────────────────────────────────────────────────────────────
def weapon_power(run):
    return 2 * run.wlevel + power(run.gear[G_WEAPON])


def armor_power(run):
    d = 4 + 3 * run.alevel
    for s in range(NSLOT):
        if s != G_WEAPON:
            d += power(run.gear[s]) // DEF_DIV[s]
    return d


def weapon_pts(run, focus=None):
    """Weapon power after the focus split — MAMEC's weapon_efficiency. `focus` is the GOVERNING generation's,
    which is not necessarily the one currently stored on the run."""
    return weapon_power(run) * (run.focus if focus is None else focus) // 100


def armor_pts(run, focus=None):
    return armor_power(run) * (100 - (run.focus if focus is None else focus)) // 100


# ── world derivation ─────────────────────────────────────────────────────────────────────────────
def slice_tile(tw):
    """tw (32 bits) -> (a tile class 0..99, b monster 0..63, c loot 0..63, d scenery 0..8191)."""
    a = tw % 100
    tw //= 100
    b = tw % 64
    tw //= 64
    c = tw % 64
    tw //= 64
    return a, b, c, tw % 8192


def slice_roll(rw):
    """rw (32 bits) -> (x variance 0..99, y damage 0..63, z drop 0..63)."""
    x = rw % 100
    rw //= 100
    y = rw % 64
    rw //= 64
    return x, y, rw % 64


def tile_of(a, depth):
    """The tile class entered at `depth`. Bosses override the roll on the chapter marks.

    Expressed as a count of thresholds passed, because that is literally what the contract computes —
    `sum(a >= cut for cut in TILE_CUTS)` — and the class ordering is load-bearing for it."""
    if depth > 0 and depth % BOSS_EVERY == 0:
        return BOSS
    return sum(1 for cut in TILE_CUTS if a >= cut)


def tier_of(depth):
    return depth // TIER_EVERY


def is_night(depth):
    return (depth // NIGHT_EVERY) % 2 == 1


def monster_level(tile, depth):
    ml = 1 + tier_of(depth)
    if tile == ELITE or tile == MIMIC:            # a mimic fights at elite level
        ml += 2
    elif tile == BOSS:
        ml += 4
    if is_night(depth):
        ml += 1
    if tile == HORDE:                             # many and weak: two levels down, floored at 1
        ml = max(1, ml - 2)
    return ml


# ── loot ─────────────────────────────────────────────────────────────────────────────────────────
def roll_item(c, z, depth, bonus):
    tier = min(7, tier_of(depth) + (c % 3) + bonus)
    if c % JACKPOT_EVERY == 0:            # the jackpot: ignores depth, rolls the top tier outright
        tier = 7
    mat = (c // 8) % 8
    affix = 1 + (z // 4) % 7 if z % 4 == 0 else 0
    kind = (c + z) % 4                        # WEAPON CLASS — used only if this lands in slot 0
    return pack_item(tier, mat, affix, kind)


def take_item_at(run, slot, item):
    """Auto-equip if strictly better, else melt for materials. An absent player still improves — and the
    player ADAPTS TO THE GEAR THE ROAD GIVES: no inventory, no take-backs."""
    new, old = power(item), power(run.gear[slot])
    if new > old:
        run.gear[slot] = item
        run.mats[M_SCRAP] += 1 + old // 8
        return True
    run.mats[M_SCRAP] += 1 + new // 8
    return False


def drink(run):
    """Every heal breaks the streak. That is the point: the potion that saves your life also cancels the
    multiplier you spent twelve fights building, so 'do I drink?' is never free."""
    if run.potions <= 0:
        return False
    run.potions -= 1
    run.hp = min(run.maxhp, run.hp + HEAL_BASE + 4 * tier_of(run.depth))
    if not has_affix(run, AF_HALLOW):     # hallowed: the heal no longer cancels the streak
        run.streak = 0
    return True


def try_craft(run, focus=None):
    """Auto-craft at a forge, cheapest-useful-first. Keeps an absent player progressing, exactly like
    auto-equip — MAMEC made you walk into the menu; the march does it on your behalf."""
    if focus is None:
        focus = run.focus
    s, h, e = run.mats
    want_w = run.wlevel < LEVEL_CAP and s >= SHARPEN_COST[0] and e >= SHARPEN_COST[2]
    want_a = run.alevel < LEVEL_CAP and s >= REINFORCE_COST[0] and h >= REINFORCE_COST[1]
    if want_w and (run.focus >= 50 or not want_a):
        run.mats[M_SCRAP] -= SHARPEN_COST[0]
        run.mats[M_ESSENCE] -= SHARPEN_COST[2]
        run.wlevel += 1
        return 1
    if want_a:
        run.mats[M_SCRAP] -= REINFORCE_COST[0]
        run.mats[M_HIDE] -= REINFORCE_COST[1]
        run.alevel += 1
        return 2
    return 0


# ── the fight — MAMEC's formula, ported ──────────────────────────────────────────────────────────
def fight(run, tile, b, x, y, z, agg, act, ev, stance=None, focus=None):
    """One engagement. You pull `agg` foes; you always kill them, the only question is what it costs.

    MAMEC's shape exactly: damage scales with the count, exp scales with the count AND with how hurt you
    already were (bloodlust), armour divides the damage, the weapon feeds exp rather than damage, and a
    fight that didn't hurt you heals you nothing.
    """
    if stance is None:
        stance = run.stance
    if focus is None:
        focus = run.focus
    depth = run.depth
    ml = monster_level(tile, depth)
    fam = b % 3
    bv = b // 3
    if tile == BOSS or tile == MIMIC:
        foes = 1                                  # a boss is one big thing; a mimic does not come in packs
    elif tile == HORDE:
        # twice the bodies, capped at the dial's own maximum; Dodge cannot slip a horde, it only halves
        # the pull back to the plain number
        foes = agg if act == A_DODGE else min(AGG_MAX, agg * 2)
    else:
        foes = agg
    dmg_num, exp_num, streak_gain, streak_cap = STANCES[stance]

    atk_c0, atk_c1 = FAM_ATK[fam]
    xp_c0, xp_c1 = FAM_XP[fam]
    atk_each = atk_c0 + atk_c1 * ml + (bv % 4)
    xp_each = xp_c0 + xp_c1 * ml
    if tile == BOSS:
        atk_each *= 4
        xp_each *= 12
    elif tile == MIMIC:                           # bites twice its family's weight, pays 4x the renown
        atk_each *= 2
        xp_each *= 4

    # ---- damage in ------------------------------------------------------------------------------
    # Absorption is PER ENGAGEMENT, not per foe and not a percentage. Armour eats one swing's worth, so a
    # small pull can be free while a horde always draws blood no matter how armoured you are. That is the
    # whole tension: armour buys you safe chip-farming, never safe greed.
    #   * flat % cut (draft 1) → the dial was a pure death switch with a cliff between agg 2 and 4;
    #   * per-FOE absorb (draft 2) → armour nullified everything, focus=0 survived 59/60 and dominated.
    atk_each = atk_each * dmg_num // 4                    # stance
    if act == A_STRIKE:
        atk_each = atk_each * 5 // 4
    atk_each = atk_each * (100 + (x % 21) - 10) // 100    # ±10% variance
    # A horde ALWAYS draws blood: at least 1 hp per foe, no matter how armoured you are. Without this
    # floor, enough armour nullifies any pull and greed becomes free — which is exactly what the sim found.
    absorb = armor_pts(run, focus) * (foes if has_affix(run, AF_HEAVY) else 1)   # heavy: absorb every swing
    total = foes * atk_each
    # Guard is a SHIELD, not a fortress: it takes HALF of up to TWO foes' swings, and the rest of the pull
    # hits you full. A duel or a boss is truly halved; a greedy eight-pull is barely dented. Flat -50% on
    # everything made "aggressive pull + always guard" the dominant strategy in the sim (all-guard brush:
    # 79/80 survival, 2x every reading pilot) — and no renown tax fixed it, because the win was survival.
    if act == A_GUARD:
        total = c_sub(total, min(foes, 2) * (atk_each // 2))
    dmg = c_sub(total, absorb)
    if dmg < foes:
        dmg = foes

    # ---- renown out (bloodlust is computed on the hp you went IN with) ---------------------------
    hp_before = run.hp
    # The focus slider has to be a genuine trade, so the two halves buy different currencies: armour buys
    # survival (absorb, above), the weapon MULTIPLIES renown. When the weapon only fed MAMEC's veteran
    # bonus, armour was strictly better and every sim converged on focus 0-25.
    wp = weapon_pts(run, focus)
    base = foes * xp_each * (HORDE_DIV + foes) // HORDE_DIV       # superlinear in the pull
    base = base * (8 + wp) // 8                                   # weapon scales everything you earn
    base += wp * run.kills // 64                                  # MAMEC's veteran bonus, kept small
    base = base * exp_num // 4
    if act == A_STRIKE:
        base = base * 5 // 4

    # Bloodlust: ×1 at full hp, ×5 at death's door. MAMEC's ×3 was calibrated for a 50-turn run where dying
    # cost you little; over a 512-step chapter it did not cover the risk, and the sim showed healing EARLY
    # (<70%) out-earning riding the edge (<20%) — the exact opposite of the intended tension.
    bl = run.maxhp + 4 * c_sub(run.maxhp, hp_before)
    gain = base * bl // run.maxhp

    # Greed streak: every fight since your last heal compounds the payout, up to x4. Bloodlust pays you for
    # being hurt; the streak pays you for REFUSING TO FIX IT. Together they are what make the standing-order
    # threshold the hardest number in the game.
    # AMBUSH danger pay (+25% renown) and the GALE amplifier (+25% renown out AND +25% damage in),
    # applied in the contract's exact spot: after bloodlust, before the streak.
    if tile == AMBUSH:
        gain = gain * 5 // 4
    if run.gale > 0:
        gain = gain * 5 // 4
        dmg = dmg * 5 // 4
    if run.pyre > 0:                   # the lit beacon: +25% renown, no damage rider — the gale's kind twin
        gain = gain * 5 // 4

    # WEAPON CLASS — the equipped weapon rewrites the engagement against a different axis of the road,
    # applied after every environmental rider and before the streak so it stacks the same way. Kept to the
    # game's ×5/4 / ×3/2 / ×3/4 quantum.
    wk = weapon_kind(run)
    if wk == W_AXE:                    # aggressor: +25% renown AND +25% damage taken
        gain = gain * 5 // 4
        dmg = dmg * 5 // 4
    elif wk == W_MAUL:                 # crusher: fells the big ones, clumsy in a crowd
        if tile in (BOSS, ELITE, MIMIC):
            gain = gain * 3 // 2
        elif foes > 1:
            gain = gain * 3 // 4
    elif wk == W_SPEAR:               # skirmisher: keeps a pack at bay, poor in a duel
        if foes > 1:
            dmg = dmg * 3 // 4
        else:
            gain = gain * 3 // 4

    streak = min(streak_cap + KEEN_BONUS * has_affix(run, AF_KEEN), run.streak)
    gain = gain * (STREAK_DIV + streak) // STREAK_DIV
    if act != A_GUARD:                 # no momentum behind a shield: guarded fights pause the streak
        run.streak += streak_gain

    # drinking forfeits your offence: you eat the exchange and earn nothing from it. This zeroed only the
    # event field before, so the model still banked the renown while the contract did not.
    if act == A_POTION:
        gain = 0
    run.kills += foes
    run.xp += gain
    ev["ml"], ev["fam"], ev["foes"], ev["dmg"], ev["gain"], ev["streak"] = ml, fam, foes, dmg, gain, run.streak

    # ---- materials: MAMEC's 80% drop chance per foe, made deterministic --------------------------
    drops = (foes * 4 + (z % 5)) // 5
    if drops:
        run.mats[FAM_MAT[fam]] += drops
        ev["drops"], ev["mat"] = drops, FAM_MAT[fam]

    # ---- hp: damage, then renown regen, then the easy-win clamp ---------------------------------
    regen = min(run.maxhp // REGEN_CAP_DIV, run.xp // REGEN_DIV)
    drain = wp * foes // LIFESTEAL_DIV * (1 + has_affix(run, AF_VAMP))   # lifesteal per BODY — sustain that keeps the streak
    hp = c_sub(hp_before + regen + drain, dmg)
    ev["drain"] = drain
    hp = c_sub(hp, y % 2)
    if hp >= hp_before:
        hp = c_sub(hp_before, y % 2)              # "easy win! no healing."
        ev["easy"] = 1
    run.hp = min(run.maxhp, hp)

    if tile in (BOSS, ELITE, MIMIC) or z % 4 == 0 or has_affix(run, AF_BLAZE):
        bonus = 2 if tile in (BOSS, MIMIC) else (1 if tile == ELITE else 0)   # a mimic IS treasure
        # (b + z) % 64, not b ^ z: the zkVM has no XOR opcode, and the reference model may only use
        # operations the contract can actually execute. Mixing by addition is field-native and just as
        # uncorrelated here, since b and z come from two independent hash windows.
        item, slot = roll_item((b + z) % 64, z, depth, bonus), z % NSLOT
        take_item_at(run, slot, item)
        ev["item"], ev["slot"] = item, slot
    if tile == BOSS:
        # A checkpoint. Everything you are carrying becomes untouchable, which is why the run between two
        # bosses is the unit of tension: push for one more multiplier, or make it to the bank alive.
        run.banked = run.xp
        run.maxhp += 10
        run.potions = min(POTION_CAP, run.potions + 1)
        ev["banked"] = run.banked


# ── the step ─────────────────────────────────────────────────────────────────────────────────────
def step(run, tw, rw, agg=None, stance=None, focus=None, healpct=None, action=A_DEFAULT):
    """Advance the run one tile. `tw`/`rw` are the two 32-bit hash windows.

    `action` is YOUR ANSWER to this exact tile — one 3-bit symbol of the leg's committed word, and the only
    action channel there is (manual-only: the tile-class doctrine and auto-march are gone). Zero is itself
    an action, A_DEFAULT: walk in and fight plainly. The DIALS (agg/stance/focus/healpct) default to the
    run's own; the caller passes them explicitly to model a leg governed by an older generation — the
    contract does the same through its POLH fence.

    This function and the contract's step loop are the same program written twice.
    """
    if not run.alive or run.done or run.retired:
        return {"tile": ROAD, "skip": True}
    if agg is None:
        agg = run.agg
    if stance is None:
        stance = run.stance
    if focus is None:
        focus = run.focus
    if healpct is None:
        healpct = run.healpct

    depth = run.depth
    a, b, c, scen = slice_tile(tw)
    x, y, z = slice_roll(rw)
    tile = tile_of(a, depth)
    tier = tier_of(depth)

    act = action & 7

    # A fork is a choice, not an event: the road splits and A_RIGHT takes the greedier lane, which re-rolls
    # as an elite.
    if tile == FORK:
        tile = ELITE if act == A_RIGHT else MONSTER
        act = A_DEFAULT
    # TOLLGATE robbery is the same shape: Strike cracks the reeve's strongbox and the STRONGBOX BITES —
    # a MIMIC fight (one body, elite level, double teeth, 4x renown, always drops). The Strike stays the
    # answer. Same pre-pricing spot as the fork.
    if tile == TOLLGATE and act == A_STRIKE:
        tile = MIMIC

    # Stamina regenerates before the reaction is priced, so a queued action can be paid for by the regen
    # of the very step it fires on.
    run.stam = min(STAM_MAX, run.stam + 1 + SWIFT_BONUS * has_affix(run, AF_SWIFT))
    cost = COST[act]
    if stance == ST_EVASIVE and act in (A_DODGE, A_SPRINT):
        cost -= 1                                 # evasive footwork: the skips are the stance's identity
    if cost > run.stam:                           # unaffordable reactions degrade; they never revert
        act = A_DEFAULT
    else:
        run.stam -= cost
    if agg < 1:
        agg = 1
    elif agg > AGG_MAX:
        agg = AGG_MAX

    ev = {"tile": tile, "act": act, "agg": agg, "dmg": 0, "gain": 0, "item": 0, "slot": -1}
    combat = tile in (MONSTER, HORDE, ELITE, AMBUSH, MIMIC, BOSS)
    # Sprint always slips a tile. Dodge slips too — EXCEPT a horde: too many bodies, it only halves the
    # pull (see fight()). That asymmetry is what finally gives Sprint a tile where it is the right answer.
    skip = act == A_SPRINT or (act == A_DODGE and tile != HORDE)

    # The reaction and the tile are INDEPENDENT: healing on a shrine tile still lets the shrine heal, and
    # drinking mid-fight still means you eat the exchange. (An earlier elif chain let Rally/Rest/Potion
    # swallow the tile entirely, which the contract never did.) The three are mutually exclusive anyway —
    # `act` holds one value — so only one of these bodies can fire.
    if act == A_RALLY:                            # the only heal that KEEPS the streak — the skill line.
        run.hp = min(run.maxhp, run.hp + RALLY_BASE + tier)   # it pays its FULL 3 stamina: the old +2
        ev["rally"] = 1                                        # refund made all-rally self-sustaining
    if act == A_REST:                             # MAMEC's rest: buy hp with score. At a CAMP the fire is
        camp = tile == CAMP                       # already laid: heal DOUBLES and the renown price is waived
        heal = (8 + run.xp // 32) * (2 if camp else 1)
        run.hp = min(run.maxhp, run.hp + heal)
        if not camp:
            run.xp = c_sub(run.xp, 4 + run.xp // 20)
        run.banked = min(run.banked, run.xp)      # you cannot rest away more than you still have
        run.streak = 0
        ev["rest"] = heal
        if camp:
            ev["camp"] = 1
    # at an idol the flask is an OFFERING, at a well it is BOTTLED — neither is a drink
    if act == A_POTION and tile != IDOL and tile != WELL:
        ev["drank"] = 1 if drink(run) else 0

    # AMBUSH strikes first: an armour-free sting of 2 per level unless the answer was Guard (brace) or
    # Dodge (slip). It lands even on a Sprint-past — running through an ambush is running through an ambush.
    if tile == AMBUSH and act not in (A_GUARD, A_DODGE):
        sting = 2 * monster_level(tile, depth)
        run.hp = c_sub(run.hp, sting)
        ev["sting"] = sting

    # the TOLLGATE'S LASH: dashing past the chain (Dodge or Sprint) skips the toll but not the whip —
    # an armour-free 2+2*tier, landed here because the skip path never reaches the tile body at all
    if tile == TOLLGATE and act in (A_DODGE, A_SPRINT):
        lash = 2 + 2 * tier
        run.hp = c_sub(run.hp, lash)
        ev["lash"] = lash

    # GALE arms the storm for the next three steps (the end-of-step decay eats one on this very tile,
    # hence 4) — unless you answered Dodge and sheltered through it.
    if tile == GALE and act != A_DODGE:
        run.gale = 4
        ev["gale"] = 1

    if not skip:
        if combat:
            fight(run, tile, b, x, y, z, agg, act, ev, stance, focus)
        elif tile == HAZARD:
            took = 2 + 2 * tier + (y % 6)
            if stance == ST_EVASIVE:
                took //= 2
            took = c_sub(took, armor_pts(run, focus) // 8)
            if has_affix(run, AF_WARD):           # warding: hazards do nothing at all
                took = 0
            run.hp = c_sub(run.hp, took)
            ev["dmg"] = took
        elif tile in (CACHE, RELIC, BARROW, ARMORY):
            # one merged loot family: they differ in the roll's bonus (relic +3, barrow +1), the slot
            # (armory is FORCED to the weapon rack), and whether the dead mind being robbed
            item = roll_item(c, z, depth, 3 if tile == RELIC else (1 if tile == BARROW else 0))
            slot = G_WEAPON if tile == ARMORY else z % NSLOT
            take_item_at(run, slot, item)
            ev["item"], ev["slot"] = item, slot
            if tile == BARROW:                    # the grave-curse: straight through armour; Guard braces
                curse = 2 + 2 * tier              # it to half, warding voids it. You always dig first.
                if act == A_GUARD:
                    curse //= 2
                if has_affix(run, AF_WARD):
                    curse = 0
                run.hp = c_sub(run.hp, curse)
                ev["curse"] = curse
        elif tile == SNARE:
            if act == A_GUARD:                    # spring it on the shield: no loss, +2 scrap of broken iron
                run.mats[M_SCRAP] += 2
                ev["sprung"] = 1
            else:
                run.stam = c_sub(run.stam, 3)
                ev["snare"] = 1
        elif tile == QUAG:
            took = 1 + tier                       # armour is useless in a bog; Evasive wades it halved
            if stance == ST_EVASIVE:
                took //= 2
            run.hp = c_sub(run.hp, took)
            run.stam = c_sub(run.stam, 2)
            ev["quag"] = took
        elif tile == TOLLGATE:                    # walked through (Strike re-rolled it into the MIMIC
            toll = 4 + run.xp // 32               # fight up top): the reeve takes ~3% of the whole pile
            run.xp = c_sub(run.xp, toll)
            run.banked = min(run.banked, run.xp)
            ev["toll"] = toll
        elif tile == VEIN:
            if act == A_STRIKE:                   # swing the pick: the deep lodes pay double-digit scrap
                mined = 4 + 2 * tier + z % 3
                run.mats[M_SCRAP] += mined
                ev["mined"] = mined
        elif tile == GROVE:
            if act == A_RALLY:                    # commune: essence + the spirits KEEP YOUR MOMENTUM (+1 streak)
                essence = 2 + tier // 2 + z % 2
                run.mats[M_ESSENCE] += essence
                run.streak += 1
                ev["commune"] = essence
        elif tile == WELL:
            if act == A_REST:                     # drink deep: stamina to FULL plus a small heal (the rest
                run.stam = STAM_MAX               # itself already broke the streak and spent renown above)
                run.hp = min(run.maxhp, run.hp + SHRINE_BASE // 2 + 2 * tier)
                ev["well"] = 1
            elif act == A_POTION:                 # bottle the spring: +1 flask, nothing drunk, streak kept
                run.potions = min(POTION_CAP, run.potions + 1)
                ev["bottled"] = 1
        elif tile == PYRE:
            if act == A_STRIKE:                   # light the beacon: 3 amplified steps after this one's decay
                run.pyre = 4
                ev["pyre"] = 1
        elif tile == IDOL:
            base = (20 + 20 * tier) * (run.maxhp + 4 * c_sub(run.maxhp, run.hp)) // run.maxhp
            if act == A_STRIKE:                   # smash: bloodlust-scaled renown
                run.xp += base
                ev["gain"] = base
            elif act == A_POTION and run.potions > 0:   # offer the flask: triple, flask gone
                run.xp += base * 3
                run.potions -= 1
                ev["gain"] = base * 3
                ev["offered"] = 1
        elif tile == SHRINE:
            run.hp = min(run.maxhp, run.hp + SHRINE_BASE + 4 * tier)
            run.potions = min(POTION_CAP, run.potions + (1 if z % 4 == 0 else 0))
            run.streak = 0                        # a shrine is a heal like any other — it costs the streak
            ev["heal"] = 1
        elif tile == FORGE:
            ev["craft"] = try_craft(run, focus)
            if run.mats[M_SCRAP] >= POTION_PRICE and run.potions < POTION_CAP:
                run.mats[M_SCRAP] -= POTION_PRICE
                run.potions += 1
                ev["bought"] = 1

    run.gale = c_sub(run.gale, 1)                 # the storm blows itself out one step at a time
    run.pyre = c_sub(run.pyre, 1)                 # …and the beacon burns down the same way

    # Standing order: auto-drink once hp drops under the threshold. This is what keeps an absent player
    # alive through a bad leg — and under bloodlust, choosing the threshold is the sharpest decision in
    # the game: heal early and you earn nothing, heal late and the run is over.
    if run.hp > 0 and run.potions > 0 and run.hp * 100 < run.maxhp * healpct:
        if drink(run):
            ev["auto"] = 1

    run.depth = depth + 1
    if run.hp == 0:
        run.alive = 0
        ev["died"] = 1
    elif run.depth >= CHAPTER:
        run.done = 1
        ev["chapter"] = 1
    return ev
