/*
 * Cross-check that static/pets-genes.js (what the browser SHOWS: species, stats, training odds, battle
 * outcomes) equals the Python reference in tests/test_pets_contract.py (what the CONTRACT pays on),
 * byte-for-byte, over vectors generated by Python. A drift here would render a Dragon that the chain
 * says is a Poodle. Run:  python3 tests/pets_js_crosscheck_gen.py | node tests/pets_js_crosscheck.mjs
 */
// static/nadodapp.js (imported by pets-genes.js) wires DOM listeners at module load: give node an inert DOM stub
// BEFORE importing it, or the import throws "document is not defined" and no vector is ever checked.
const _el = new Proxy(function () {}, { get: (t, k) => k === Symbol.toPrimitive ? () => "" : _el, apply: () => _el });
for (const k of ["document", "window", "localStorage", "sessionStorage", "location", "history"]) if (!(k in globalThis)) globalThis[k] = _el;
// static/ modules import the relay's /protocol.js (protocol.CLIENT_EXPORTS); tests/protocol_hook.mjs serves it
// rendered from protocol.py, and the static/ modules are loaded AFTER it (dynamic import) so they resolve through it.
import "./protocol_hook.mjs";
const { loadCrypto } = await import("../static/nadotx.js");
const G = await import("../static/pets-genes.js");

await loadCrypto(".");
let body = "";
for await (const chunk of process.stdin) body += chunk;
const V = JSON.parse(body);

let fails = 0, n = 0;
const eq = (name, got, want) => { n++; if (String(got) !== String(want)) { fails++; console.log(`FAIL ${name}: got ${got} want ${want}`); } };

for (const v of V.hatches) {
  const gene = G.geneOf(v.bh0, v.bh1, v.pid);
  eq(`gene(${v.pid})`, gene, v.gene);
  const sp = G.speciesOf(gene);
  eq(`species(${v.pid})`, sp, v.sp);
  eq(`si(${v.pid})`, G.speciesIdOf(gene, sp), v.si);
  eq(`tierOfSi(${v.pid})`, G.tierOfSi(v.si), v.sp);      // roster band must agree with the tier roll
  eq(`stats(${v.pid})`, G.baseStats(gene, sp).join(","), v.stats.join(","));
  eq(`power(${v.pid})`, G.powerOf(gene, sp), v.pw);
}
for (const v of V.trainings) {
  const roll = G.trainRollOf(v.bh0, v.bh1, v.pid, v.i);
  eq(`troll(${v.pid},${v.i})`, roll, v.roll);
  eq(`tok(${v.pid},${v.i})`, G.trainOk(roll, v.cur, v.sp), v.ok);
}
for (const v of V.battles) {
  const b = G.battleOf(v.bh0, v.bh1, v.bid, v.effA, v.effB);
  eq(`battle(${v.bid}) winner`, b.aWins, v.aWins);
  eq(`battle(${v.bid}) dies`, b.dies, v.dies);
  eq(`battle(${v.bid}) final HP`, b.h0 + "/" + b.h1, v.hp0 + "/" + v.hp1);
}
for (const v of V.crBattles || []) {
  const seed = G.battleSeedOf(BigInt(v.s1), BigInt(v.s2), v.bid);
  eq(`crSeed(${v.bid})`, seed, v.seed);
  const b = G.battleOfSeed(seed, v.bid, v.effA, v.effB);
  eq(`crBattle(${v.bid}) winner`, b.aWins, v.aWins);
  eq(`crBattle(${v.bid}) dies`, b.dies, v.dies);
  eq(`crBattle(${v.bid}) final HP`, b.h0 + "/" + b.h1, v.hp0 + "/" + v.hp1);
}
console.log(fails ? `${fails}/${n} CHECKS FAILED` : `ALL ${n} JS<->PY CHECKS PASS`);
process.exit(fails ? 1 : 0);
