/*
 * Cross-check that static/pets-genes.js (what the browser SHOWS: species, stats, training odds, battle
 * outcomes) equals the Python reference in tests/test_pets_contract.py (what the CONTRACT pays on),
 * byte-for-byte, over vectors generated by Python. A drift here would render a Dragon that the chain
 * says is a Poodle. Run:  python3 tests/pets_js_crosscheck_gen.py | node tests/pets_js_crosscheck.mjs
 */
import { loadCrypto } from "../static/nadotx.js";
import * as G from "../static/pets-genes.js";

await loadCrypto(".");
let body = "";
for await (const chunk of process.stdin) body += chunk;
const V = JSON.parse(body);

let fails = 0, n = 0;
const eq = (name, got, want) => { n++; if (String(got) !== String(want)) { fails++; console.log(`FAIL ${name}: got ${got} want ${want}`); } };

for (const v of V.hatches) {
  const gene = G.geneOf(v.bh0, v.bh1, v.pid);
  eq(`gene(${v.pid})`, gene, v.gene);
  const sp = G.speciesOf(gene);
  eq(`species(${v.pid})`, sp, v.sp);
  eq(`stats(${v.pid})`, G.baseStats(gene, sp).join(","), v.stats.join(","));
  eq(`power(${v.pid})`, G.powerOf(gene, sp), v.pw);
}
for (const v of V.trainings) {
  const roll = G.trainRollOf(v.bh0, v.bh1, v.pid, v.i);
  eq(`troll(${v.pid},${v.i})`, roll, v.roll);
  eq(`tok(${v.pid},${v.i})`, G.trainOk(roll, v.cur, v.sp), v.ok);
}
for (const v of V.battles) {
  const b = G.battleOf(v.bh0, v.bh1, v.bid, v.pwA, v.pwB);
  eq(`battle(${v.bid}) winner`, b.aWins, v.aWins);
  eq(`battle(${v.bid}) dies`, b.dies, v.dies);
  eq(`battle(${v.bid}) scores`, b.scoreA + "/" + b.scoreB, v.scoreA + "/" + v.scoreB);
}
console.log(fails ? `${fails}/${n} CHECKS FAILED` : `ALL ${n} JS<->PY CHECKS PASS`);
process.exit(fails ? 1 : 0);
