/*
 * Cross-check that static/shielded.js hashes BYTE-IDENTICALLY to execnode/shielded.py (doc/privacy.md).
 * The reference hashes are generated by the Python module; if the browser port drifts by even one byte, a
 * note committed in the browser would be rejected by the pool. Run: node tests/shielded_js_crosscheck.mjs
 *
 * Uses the SAME vendored @noble blake2b the browser loads, composed with the SAME canonicalize as miner.js.
 */
import { blake2b, bytesToHex } from "../static/vendor/nado-crypto.js";
import * as shielded from "../static/shielded.js";

// --- canonicalize + blake2bHash: copied verbatim from miner.js (itself byte-verified against Python) ---
function jsonEscapeAscii(s) { return JSON.stringify(s); }        // inputs here are ASCII -> JSON string literal
function canonicalize(data) {
  if (data === null || data === undefined) return "null";
  const t = typeof data;
  if (t === "boolean") return data ? "true" : "false";
  if (t === "bigint") return data.toString();
  if (t === "number") { if (!Number.isInteger(data)) throw new Error("float"); return String(data); }
  if (t === "string") return jsonEscapeAscii(data);
  if (Array.isArray(data)) return "[" + data.map(canonicalize).join(",") + "]";
  if (t === "object") { const k = Object.keys(data).sort(); return "{" + k.map((x) => jsonEscapeAscii(x) + ":" + canonicalize(data[x])).join(",") + "}"; }
  throw new Error("bad type " + t);
}
const _enc = new TextEncoder();
const blake2bHash = (data, size = 32) => bytesToHex(blake2b(_enc.encode(canonicalize(data)), { dkLen: size }));
shielded.initShielded(blake2bHash);

// --- reference values generated by execnode/shielded.py ---
const REF = {
  owner:    "73fa3f0c2dd6ece1ec9150cb15187084b1d13bb2d20f49bc9f842a5257572a3d",
  cm:       "164ef819740d06d8dde1ac10708cc7a4d49d0bd16775f29bef4b709a249f3ed2",
  nf:       "63390052db182345d0408f6b973261773aefab71a647a87408a74273ad5fe91d",
  sighash:  "8dbdb4453fa3ac7ba513695ea170c49f8ecda7ee820396d1825ad34843eb5eec",
  empty:    "f83501daa1f2c0d57a32b3562f4dd1341061ce9cfd6397ff32b286e6e2740d31",
  root3:    "373d169e713e2448cd138c1b090aa14a6d4f9d1f8985a25436e715625b02c8f1",
};

let fails = 0;
function eq(name, got, want) {
  const ok = got === want;
  if (!ok) fails++;
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}${ok ? "" : `\n   got  ${got}\n   want ${want}`}`);
}

const owner = shielded.ownerId("abcd1234");
eq("owner_id", owner, REF.owner);
eq("note_commitment", shielded.noteCommitment(100, owner, "rho1"), REF.cm);
eq("note_nullifier", shielded.noteNullifier("abcd1234", "rho1"), REF.nf);
eq("transfer_sighash", shielded.transferSighash({ nullifiers: ["nfB", "nfA"], out_commitments: ["cm2", "cm1"], public_value: -40, fee: 10 }), REF.sighash);
eq("empty_root", shielded.emptyRoot(), REF.empty);

const leaves = [10, 20, 30].map((v) => shielded.noteCommitment(v, owner, "r" + v));
eq("merkle_root(3)", shielded.merkleRoot(leaves), REF.root3);
const path = shielded.merklePath(leaves, 1);
eq("merkle_path len", String(path.length), "32");
eq("verify_path(pos1)", String(shielded.verifyPath(leaves[1], 1, path, shielded.merkleRoot(leaves))), "true");
eq("verify_path(wrong pos rejected)", String(shielded.verifyPath(leaves[1], 0, path, shielded.merkleRoot(leaves))), "false");

console.log(`\n${fails ? fails + " FAILED — JS and Python DIVERGE" : "ALL PASSED — JS ≡ Python byte-for-byte"}`);
process.exit(fails ? 1 : 0);
