/*
 * stormhold_next_move.mjs — LIVE-chain move oracle for the Stormhold E2E: reads the game's on-chain move
 * log + the L1 block hashes it pins, replays it through the REAL engine (exactly what the browser does),
 * and prints ONE line of JSON: either the next legal move for the current actor (generated by the shared
 * bot), or the game's terminal/blocked status. The python driver submits the move with the right key.
 * Usage: node tests/stormhold_next_move.mjs <gameId> <cid> [seed] [execUrl]
 */
import { prng, randomMove } from "./stormhold_bot.mjs";
const E = await import("../static/stormhold-engine.js");

const [g, cid, seedArg, exec] = [process.argv[2], process.argv[3], process.argv[4] || "1", process.argv[5] || "http://127.0.0.1:9273"];
const out = (o) => { console.log(JSON.stringify(o)); process.exit(0); };
const J = async (u) => (await fetch(u)).json();

const sto = (await J(`${exec}/exec/contract?ns=default&cid=${cid}&provisional=1`)).storage || {};
const m = (n) => sto[n] || {};
const nn = m("nn")[g] || 0, mc = m("mc")[g] || 0, kh = m("kh")[g] || 0;
if (nn < 2 || !kh) out({ waiting: "join" });
const recs = [];
for (let i = 0; i < mc; i++) {
  const enc = m("mv")[String(g * 10000 + i)], rec = m("mh")[String(g * 10000 + i)];
  if (!enc || !rec) out({ waiting: "log" });
  recs.push({ enc, side: rec % 4, rh: Math.floor(rec / 4) });
}
const heights = [kh, kh + 1, ...recs.flatMap((r) => [r.rh, r.rh + 1])];
const bh = (await J(`${exec}/exec/blockhash?ns=default&provisional=1&heights=${[...new Set(heights)].join(",")}`)).hashes || {};
const qOf = (h) => (bh[String(h)] && bh[String(h + 1)]) ? BigInt("0x" + bh[String(h)]) + BigInt("0x" + bh[String(h + 1)]) : null;

const st = E.replay(Number(g), qOf(kh), recs.map((r) => ({ enc: r.enc, side: r.side, q: qOf(r.rh) })));
if (st.setup || st.blocked) out({ blocked: true, at: st.blockedAt });
if (st.corrupt) out({ corrupt: true, why: st.corruptWhy });
if (st.over) out({ over: true, result: st.result, vp: [E.scoreOf(st, 0), E.scoreOf(st, 1)], mc });
const mv = randomMove(st, prng((Number(seedArg) * 7919 + mc) >>> 0));
out({ actor: mv.side - 1, enc: mv.enc, ply: mc, phase: st.phase, frames: st.frames.length,
      vp: [E.scoreOf(st, 0), E.scoreOf(st, 1)] });
