"""THE I18N GENERATOR REFUSES the source shapes that used to ship broken strings (tools/build_i18n.py).

i18n.js was hand-layered until 2026-10-10 and 129 keys were defined more than once (the last silently won). The
generator makes each failure a refusal instead of a surprise. Pins, each on a throwaway source set:
  * a key defined in two files is refused (the layering bug);
  * a language whose key set drifts from `en` is refused (a silent English fallback);
  * a {placeholder} that differs from `en` in any language is refused (a literal "{t}" on screen);
  * an empty string is refused (t() treats "" as missing);
  * a file without all 16 languages is refused;
  * a clean set builds, every language carrying every key, in the generated output;
  * and the real tree builds clean and the committed i18n.js is exactly its output.
Pure: reads JSON and writes nothing outside a temp dir. Run: python3 tests/test_i18n_generator_refuses_bad_sources.py
"""
import json
import os
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import build_i18n as B  # noqa: E402

fails = 0


def check(name, ok, detail=""):
    global fails
    print(("PASS  " if ok else "FAIL  ") + name + ("" if ok else f"  {detail}"))
    fails += 0 if ok else 1


D = tempfile.mkdtemp(prefix="nado-i18n-gen-")


def src(name, per_lang):
    p = os.path.join(D, name)
    json.dump(per_lang, open(p, "w", encoding="utf-8"), ensure_ascii=False)
    return p


def full(table):
    return {l: dict(table) for l in B.LANGS}


def refused(files, needle):
    try:
        B.load_and_validate(files)
    except B.I18nError as e:
        return needle in str(e), str(e)[:200]
    return False, "accepted"


good = src("good.json", full({"a.x": "Hello {n}", "a.y": "Bye"}))
check("a clean source set builds", B.load_and_validate([good])["cs"] == [("a.x", "Hello {n}"), ("a.y", "Bye")])

dup = src("dup.json", full({"a.x": "Again"}))
check("a key defined in two files is refused", *refused([good, dup], "duplicate key 'a.x'"))

drift = full({"b.x": "One", "b.y": "Two"})
del drift["ja"]["b.y"]
check("a language missing a key that en has is refused", *refused([src("drift.json", drift)], "ja key set drifts"))

ph = full({"c.x": "Sent {amt} to {to}"})
ph["de"]["c.x"] = "{amt} gesendet an {t}"
check("a placeholder differing from en is refused", *refused([src("ph.json", ph)], "c.x [de] placeholders"))

empty = full({"d.x": "Text"})
empty["vi"]["d.x"] = ""
check("an empty string is refused", *refused([src("empty.json", empty)], "d.x [vi] is empty"))

short = full({"e.x": "Text"})
del short["ar"]
check("a file without all 16 languages is refused", *refused([src("short.json", short)], "missing ['ar']"))

tmpl = open(B.TEMPLATE, encoding="utf-8").read()
out = B.render(B.load_and_validate([good]), tmpl)
check("the rendered file carries every key in every language",
      all(f"    {l}: {{\n" in out for l in B.LANGS) and out.count('"a.y": "Bye"') == len(B.LANGS))
check("the rendered file says it is generated", "GENERATED by tools/build_i18n.py" in out and "@@" not in out)

try:
    real = B.build()
    check("the real sources build clean", True)
    check("the committed static/i18n.js is exactly the generator's output",
          real == open(B.OUT, encoding="utf-8").read(), "run python3 tools/build_i18n.py")
except B.I18nError as e:
    check("the real sources build clean", False, str(e)[:400])

print("ALL PASS" if not fails else f"{fails} FAILURES")
sys.exit(1 if fails else 0)
