// swift-tools-version: 5.5
// Swift Playgrounds (iPad) app package — GENERATED by make_playground.py from ../NadoAttest/*.swift. Do not edit the
// Swift files here; edit the originals and regenerate. Shape = what Playgrounds itself generates (no teamIdentifier
// until signed in, placeholder icon, tools 5.5), so the app opens on any Playgrounds 4.x.
import PackageDescription
import AppleProductTypes

let package = Package(
    name: "NadoAttest",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "NadoAttest",
            targets: ["AppModule"],
            bundleIdentifier: "com.nadochain.attest",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .bicycle),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
