// swift-tools-version: 5.9
// Swift Playgrounds (iPad) app package — GENERATED by make_playground.py from ../NadoAttest/*.swift. Do not edit the
// Swift files here; edit the originals and regenerate.
import PackageDescription
import AppleProductTypes

let package = Package(
    name: "NadoAttest",
    platforms: [.iOS("16.0")],
    products: [
        .iOSApplication(
            name: "NadoAttest",
            targets: ["AppModule"],
            bundleIdentifier: "com.nadochain.attest",
            teamIdentifier: "",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .lock),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [.pad, .phone],
            supportedInterfaceOrientations: [.portrait],
            appCategory: .utilities
        )
    ],
    targets: [
        .executableTarget(name: "AppModule", path: ".")
    ]
)
