#!/usr/bin/env python3
"""Generate NadoAttest.swiftpm — the Swift Playgrounds (iPad) app package — from NadoAttest/*.swift. Run after
editing any Swift source; the generated folder is committed so an iPad can clone the repo (Working Copy) and open it
without a Mac. Playgrounds can run the app on the iPad itself and, with a paid developer account signed in, upload it
to App Store Connect. What it cannot do, as far as Apple documents: add the App Attest entitlement — pressing Attest
in a Playgrounds build answers the open question "does App Attest work without the capability?" live."""
import os, shutil
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "NadoAttest")
OUT = os.path.join(HERE, "NadoAttest.swiftpm")
os.makedirs(OUT, exist_ok=True)
for f in os.listdir(OUT):
    if f.endswith(".swift") and f != "Package.swift":
        os.remove(os.path.join(OUT, f))
for f in sorted(os.listdir(SRC)):
    if f.endswith(".swift"):
        shutil.copyfile(os.path.join(SRC, f), os.path.join(OUT, f))
open(os.path.join(OUT, "Package.swift"), "w").write('''// swift-tools-version: 5.5
// Swift Playgrounds (iPad) app package — GENERATED by make_playground.py from ../NadoAttest/*.swift. Do not edit the
// Swift files here; edit the originals and regenerate. Shape = what Playgrounds itself generates (no teamIdentifier
// until signed in, placeholder icon, tools 5.5), so the app opens on any Playgrounds 4.x.
import PackageDescription
import AppleProductTypes

let package = Package(
    name: "NadoAttest",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "NadoAttest",
            targets: ["AppModule"],
            bundleIdentifier: "com.nadochain.attest",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .bicycle),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
''')
print("generated", OUT, sorted(os.listdir(OUT)))
