"""
Autogame — the March. A side-scrolling warrior run whose pace IS the chain: one step per L1 block, until
the chapter concludes. Full design: doc/autogame.md.

Two ancestors. The CLOCK is Autogame (Bismuth, 2017): a world "unknowingly generated by the miners" that
every player replays from the same rules — there by convention, here by contract. The ECONOMY is MAMEC /
"math sword" (PICO-8 v1.70): a fixed budget, a risk dial you set yourself, and rules that make cowardice
unprofitable.

THE ONE MECHANISM everything rests on: a leg's TILES come from BHASH(lh) — visible the moment the previous
leg settles — and its ROLLS come from BHASH(lh + LEG), which does not exist yet while you are planning. So
you commit actions against terrain you can see, and the dice land afterward. Nobody can grind either: the
terrain height was pinned before you could see it, and the roll height is later still.

WHY LATENESS IS HARMLESS. Both hashes are already final when a leg settles, so a leg's outcome is a pure
function of chain state — settling it now or six hours from now gives the identical result. advance() is
therefore permissionless: a friend, a keeper, or you-tomorrow can walk the state forward and none of them
can change it. BHASH reaches ~20k heights back (state.record_block_hash), so a run left unsettled past that
horizon can never be resolved; that is a public, deterministic condition, so it gets a deterministic rule —
the run concludes at its last resolved step and scores what it had (`mists`).

THIS FILE IS THE DEFINITION OF THE RULES. tests/autogame_model.py imports the constants below rather than
restating them, so the readable reference model and the authoritative contract cannot drift. The JS engine
(static/autogame-engine.js) mirrors them and tests/autogame_contract_test.py asserts all three agree.

FIELD-WRAP DISCIPLINE. Goldilocks subtraction wraps, and a wrapped `hp` is a ~2^64 hit-point pool. Every
subtraction of a player- or roll-controlled quantity goes through `csub` (select(a<b, 0, a-b)), never a bare
`-`. This is the class of bug that produced the banked-table drain; check it first in any diff.
"""
from execnode import zkpy
from execnode.zkpy import hash as zhash, lo32, select

# ── clock ────────────────────────────────────────────────────────────────────────────────────────
LEG = 16                 # steps per leg == blocks per leg (1 step per block, by construction)
MAX_LEGS_PER_CALL = 2    # bounded catch-up: 32 steps/call. Measured at ~2730 trace rows per step, so 32
                         # steps is ~87k rows and 48 steps blows the 131070 ceiling. 2 is also the EFFICIENT
                         # choice, not merely the largest that fits: the trace pads to the next power of two,
                         # so a 32-step call and two 16-step calls both cost 131072 rows to prove — one call
                         # gets the same proving work done in half the transactions.
CHAPTER = 512            # steps per chapter (32 legs, ~51 min). A FIXED budget: the game is how much you
                         # extract from it, never how long you can hide.
START_GAP = 2            # begin() pins the first tile height in the FUTURE so it cannot be steered

# ── tuning ───────────────────────────────────────────────────────────────────────────────────────
HP0 = 100
STAM_MAX = 12
AGG_MAX = 16
REGEN_DIV = 20           # MAMEC's exp/20 heal …
REGEN_CAP_DIV = 8        # … capped at maxhp/8: uncapped it makes you immortal at ~2000 renown over 512 steps
BOSS_EVERY = 128         # every 128th tile is a boss — and a CHECKPOINT that banks your renown
TIER_EVERY = 32          # danger tier = depth // 32; the road must outrun your growth
NIGHT_EVERY = 64
LEVEL_CAP = 8            # crafted weapon/armour levels; uncapped, absorption outgrows the road
LIFESTEAL_DIV = 4        # weapon focus heals wp/4 per engagement — sustain that does NOT break the streak
HORDE_DIV = 4            # renown is superlinear in the pull: foes * xp_each * (4+foes)/4
STREAK_DIV = 4           # streak multiplier = (4 + streak)/4
DEATH_KEEP = 25          # % of UNBANKED renown that survives death
COMPLETE_BONUS = 200000  # flat road bonus for finishing; pro-rata on depth if you retire standing; zero if
                         # you die. Flat, not a multiplier: as a x4 it compounded with the greed streak.
POTIONS0 = 3
POTION_CAP = 5
POTION_PRICE = 10        # scrap
HEAL_BASE = 20           # potion heal = 20 + 4*tier
SHRINE_BASE = 10         # shrine heal = 10 + 4*tier
RALLY_BASE = 4           # rally heal = 4 + tier
NSLOT = 6

# tile classes. THE ORDER IS LOad-BEARING: the contract derives the class as a sum of threshold
# comparisons (see TILE_CUTS), which yields exactly this ordering, so renumbering breaks the world.
ROAD, MONSTER, ELITE, HAZARD, CACHE, SHRINE, FORGE, FORK, RELIC, BOSS = range(10)
TILE_CUTS = (30, 58, 66, 74, 82, 87, 92, 99)     # tile = sum(a >= cut) over these

# actions (3 bits each, 16 per leg => 48 bits, safely under Goldilocks P)
A_DEFAULT, A_STRIKE, A_GUARD, A_DODGE, A_POTION, A_SPRINT, A_REST, A_RIGHT = range(8)
A_RALLY = A_RIGHT        # action 7 does double duty: right lane at a FORK, Rally anywhere else
COST = (0, 2, 1, 2, 0, 3, 0, 3)

# stance -> (incoming damage /4, renown /4, streak gain per fight, streak cap)
ST_BALANCED, ST_AGGRESSIVE, ST_GUARDED, ST_EVASIVE = range(4)
STANCES = ((4, 4, 1, 12), (5, 6, 2, 20), (3, 4, 0, 0), (4, 3, 1, 8))

# monster families — MAMEC's grunt / brute / glass cannon; atk_each = c0 + c1*ml, xp_each = c0 + c1*ml
FAM_ATK = ((1, 1), (3, 3), (2, 2))
FAM_XP = ((0, 1), (0, 3), (0, 5))
M_SCRAP, M_HIDE, M_ESSENCE = range(3)

SHARPEN_COST = (2, 0, 1)      # scrap, hide, essence -> weapon +1
REINFORCE_COST = (1, 2, 0)    # -> armour +1

G_WEAPON, G_HELM, G_BODY, G_SHIELD, G_BOOTS, G_CLOAK = range(NSLOT)
DEF_DIV = (1, 4, 2, 3, 4, 4)  # slot 0 is the weapon and is skipped; 1 keeps the divisor legal

RANKS = ((60, "commoner"), (180, "apprentice"), (450, "journeyman"), (1100, "knight"),
         (2600, "banneret"), (6000, "lord"), (14000, "baron"), (32000, "duke"),
         (75000, "king"), (170000, "emperor"), (400000, "demigod"), (1 << 40, "creator"))

# ── storage map ──────────────────────────────────────────────────────────────────────────────────
# run scalars, keyed by run id
(RA, RLH, RNH, RHP, RMX, RST, RPO, RXP, RBK, RDP, RKI, RSN, RHL, RFO, RWL, RAL,
 RM0, RM1, RM2, RAV, RDN, RRT, RLG, RSK) = range(1, 25)
GEAR0 = 30                    # gear slots occupy GEAR0 .. GEAR0+5, keyed by run id
RLIST = 50                    # run-id list (count in slot 0)
OWNRUN = 51                   # caller digest -> their current run id
SC = 90                       # per-call scratch, keyed by the S_* indices below

# lookup tables written once by the constructor — one SLOAD replaces a chain of selects, and the rules
# become auditable in storage rather than buried in emitted asm
TCOST, TSDMG, TSXP, TSGAIN, TSCAP, TFA0, TFA1, TFX0, TFX1, TDEFD = range(60, 70)

PLAN_TAG, AGG_TAG = 101, 102  # hash(tag, run, leg) -> packed action word / aggression

# scratch indices
(S_A, S_B, S_C, S_X, S_Y, S_Z, S_TILE, S_ML, S_ACT, S_AGG, S_TIER, S_ATK, S_DMG, S_GAIN, S_WP, S_ABS,
 S_HPB, S_FOES, S_PW, S_I, S_T, S_R, S_LEGS, S_FAM, S_XPE, S_BASE, S_STK, S_DN, S_XN, S_SG, S_SCAP,
 S_ITEM, S_SLOT, S_COMBAT, S_SCEN, S_DROPS,
 S_T0, S_T1, S_T2, S_T3, S_T4, S_T5, S_T6,
 S_R0, S_R1, S_R2, S_R3) = range(47)
NSCRATCH = 47


# ── helpers ──────────────────────────────────────────────────────────────────────────────────────
def csub(a, b):
    """Clamped subtraction — the ONLY subtraction this contract is allowed to perform."""
    return select(a < b, 0, a - b)


def vmin(a, b):
    return select(a < b, a, b)


def vmax(a, b):
    return select(a < b, b, a)


def _r(m, field):
    """A run-scalar cell for the run id in arg 0."""
    return m.slot(field, m.arg(0))


def _s(m, i):
    """A scratch cell. Scratch is per-call working space: every read is preceded by a write in the same
    call, and advance() clears it before returning so no residue reaches the state root."""
    return m.slot(SC, i)


def park(m, i, v):
    """Compute `v` now into scratch cell `i` and hand back a cheap re-readable reference.

    The allocator has six registers, and it refuses (loudly, at build time) to compile an expression whose
    live temporaries exceed them — a nested select inside a csub is already too deep. Parking intermediates
    flattens every expression to a couple of loads, which is why this contract reads as a sequence of small
    assignments rather than one algebraic statement. It is also why a 0/1 flag is usually MULTIPLIED rather
    than selected on: `x * flag` is two live values, `select(flag, x, 0)` is four."""
    _s(m, i).set(v)
    return _s(m, i).get()


def _own_or_die(m):
    """Require the caller to own the run in arg 0."""
    m.require(_r(m, RA).get() == m.caller())


def _live(m):
    """Require the run to exist and still be running."""
    m.require(_r(m, RA).get() != 0)
    m.require(_r(m, RAV).get() == 1)
    m.require(_r(m, RDN).get() == 0)
    m.require(_r(m, RRT).get() == 0)


def _power_of(m, cell, tmp):
    """An item's power score (tier*4 + material) computed INTO scratch[tmp]; returns a cheap reference.

    An empty cell needs no special case: cells store 1 + tier*64 + mat*8 + affix, so 0 means empty, and
    csub(0, 1) is 0, which scores 0. Computed through scratch rather than as one expression because five
    of these nested inside an accumulator is far past the six-register budget."""
    _s(m, tmp).set(csub(cell.get(), 1))
    _s(m, tmp).set((_s(m, tmp).get() // 64) * 4 + (_s(m, tmp).get() // 8) % 8)
    return _s(m, tmp).get()


def _weapon_power(m, into):
    _s(m, into).set(2 * _r(m, RWL).get())
    _s(m, into).set(_s(m, into).get() + _power_of(m, m.slot(GEAR0 + G_WEAPON, m.arg(0)), S_T6))
    return _s(m, into).get()


def _armor_power(m, into):
    """4 + 3*alevel plus each non-weapon slot's contribution. Unrolled over five slots — the divisors
    differ per slot, so a loop would need a table lookup per iteration for no saving."""
    _s(m, into).set(4 + 3 * _r(m, RAL).get())
    for sl in range(1, NSLOT):
        _s(m, into).set(_s(m, into).get() + _power_of(m, m.slot(GEAR0 + sl, m.arg(0)), S_T6) // DEF_DIV[sl])
    return _s(m, into).get()


def _armor_pts(m, into):
    """Armour after the focus split — what actually absorbs."""
    _armor_power(m, into)
    _s(m, into).set(_s(m, into).get() * (100 - _r(m, RFO).get()) // 100)
    return _s(m, into).get()


def _drink(m):
    """Consume a potion if you have one: heal, and BREAK THE STREAK. Emitted at both the explicit A_POTION
    action and the standing order, because they are the same act with different triggers."""
    got = park(m, S_T3, _r(m, RPO).get() > 0)
    _r(m, RPO).set(csub(_r(m, RPO).get(), got))
    _s(m, S_T2).set(_r(m, RHP).get() + (HEAL_BASE + 4 * _s(m, S_TIER).get()) * got)
    _r(m, RHP).set(vmin(_r(m, RMX).get(), _s(m, S_T2).get()))
    _r(m, RSK).set(_r(m, RSK).get() * csub(1, got))


_LBL = [0]


def _uniq(prefix):
    """Unique label names — _take_item is inlined at several sites inside the same method. The counter is
    reset per build() so the emitted program stays deterministic (and so does the contract id)."""
    _LBL[0] += 1
    return f"{prefix}{_LBL[0]}"


def _take_item_if_any(m):
    """Skip the whole equip/melt block when nothing dropped.

    _take_item walks all six gear cells and computes an item power for each — two DIVMODs apiece — and it
    ran on EVERY step even though most tiles drop nothing. Jumping over it when S_ITEM is 0 is what brings a
    combat-heavy leg back inside the trace budget; drops are the minority of steps by a wide margin."""
    lbl = _uniq("noitem")
    m.jnz(_s(m, S_ITEM).get() == 0, lbl)
    _take_item(m)
    m.label(lbl)


def _take_item(m):
    """Auto-equip the drop in scratch[S_ITEM] if it beats what occupies scratch[S_SLOT], else melt it for
    scrap. An absent player still improves, which is the whole point of the standing-order design.

    S_ITEM == 0 means "no drop this tile" and must be a complete no-op — an earlier version still credited
    a scrap for the melt, quietly paying the player for nothing on every empty tile.

    The destination slot is roll-derived, so the write is a select over all six cells rather than a computed
    address: gear slots are enumerable flat fields, not hash-keyed."""
    any_drop = park(m, S_T5, _s(m, S_ITEM).get() != 0)
    newp = park(m, S_T4, _power_of(m, _s(m, S_ITEM), S_T6))
    for sl in range(NSLOT):
        cell = m.slot(GEAR0 + sl, m.arg(0))
        oldp = park(m, S_T3, _power_of(m, cell, S_T6))
        hit = park(m, S_T0, _s(m, S_SLOT).get() == sl)
        better = park(m, S_T1, oldp < newp)
        take = park(m, S_T2, hit * better * any_drop)
        # melt whatever did NOT get equipped: the item it replaced, or the drop itself
        _s(m, S_T1).set(select(take, oldp, newp))
        cell.set(select(take, _s(m, S_ITEM).get(), cell.get()))
        _s(m, S_T1).set((1 + _s(m, S_T1).get() // 8) * hit * any_drop)
        _r(m, RM0).set(_r(m, RM0).get() + _s(m, S_T1).get())


def _roll_item(m, mixed, bonus):
    """tier = min(7, tier + mixed%3 + bonus); mat = (mixed/8)%8; affix is rare. Stored as 1 + t*64 + m*8 + a.

    Uses its OWN scratch range (S_R*) rather than the shared S_T* temporaries. It used to borrow S_T0..S_T3,
    and _fight had parked its drop flag in S_T0 across the call — so the post-call `item * flag` multiplied
    the item by the freshly-written TIER instead, silently handing out items worth 2-5x their roll. The
    differential test caught it as gear values that were exact multiples of the model's."""
    _s(m, S_R0).set(_s(m, S_TIER).get() + mixed % 3)
    _s(m, S_R0).set(_s(m, S_R0).get() + bonus)
    _s(m, S_R0).set(vmin(7, _s(m, S_R0).get()))                  # tier
    _s(m, S_R1).set((mixed // 8) % 8)                            # material
    _s(m, S_R2).set(_s(m, S_Z).get() % 4 == 0)
    _s(m, S_R3).set((1 + (_s(m, S_Z).get() // 4) % 7) * _s(m, S_R2).get())   # affix, mostly none
    _s(m, S_ITEM).set(1 + _s(m, S_R0).get() * 64 + _s(m, S_R1).get() * 8 + _s(m, S_R3).get())
    _s(m, S_SLOT).set(_s(m, S_Z).get() % NSLOT)


# ── the step ─────────────────────────────────────────────────────────────────────────────────────
def _derive(m):
    """Slice the two 32-bit hash windows in exactly the documented order and park the fields in scratch.
    The reference model consumes them in the same order with the same divisors, so the bit budget cannot
    silently drift between the two implementations."""
    tw = lo32(zhash(_s(m, S_T).get(), m.arg(0), _s(m, S_I).get()))
    _s(m, S_A).set(tw % 100)
    _s(m, S_B).set((tw // 100) % 64)
    _s(m, S_C).set((tw // 6400) % 64)
    # the 4th field (scenery detail, tw//409600 % 8192) is deliberately NOT derived here: it is pure
    # presentation, the renderer recomputes it from the same hash, and its divisor exceeds DIVMOD's 2^15
    # window. Consensus pays for nothing it does not decide.

    rw = lo32(zhash(_s(m, S_R).get(), m.arg(0), _s(m, S_I).get()))
    _s(m, S_X).set(rw % 100)
    _s(m, S_Y).set((rw // 100) % 64)
    _s(m, S_Z).set((rw // 6400) % 64)


def _classify(m):
    """tile class, danger tier and monster level for the tile being entered."""
    depth = _r(m, RDP).get()
    _s(m, S_TIER).set(depth // TIER_EVERY)

    a = _s(m, S_A).get()
    klass = m.const(0)
    for cut in TILE_CUTS:                       # sum of threshold comparisons -> the class ordinal
        klass = klass + (a >= cut)
    isboss = select(depth == 0, 0, depth % BOSS_EVERY == 0)
    _s(m, S_TILE).set(select(isboss, BOSS, klass))

    # A fork is a CHOICE, not an event: the right lane re-rolls as an elite, the left as a monster.
    # `isfork` MUST be snapshotted before S_TILE is rewritten — a zkpy Val is a lazy re-read of the cell,
    # not a captured value, so testing it after the write compared the NEW tile against FORK, always came
    # out false, and the action was never cleared. A Sprint queued on a fork then paid its stamina and
    # skipped the fight the model fought.
    isfork = park(m, S_T0, _s(m, S_TILE).get() == FORK)
    _s(m, S_T1).set(select(_s(m, S_ACT).get() == A_RIGHT, ELITE, MONSTER))
    _s(m, S_TILE).set(select(isfork, _s(m, S_T1).get(), _s(m, S_TILE).get()))
    _s(m, S_ACT).set(select(isfork, A_DEFAULT, _s(m, S_ACT).get()))

    t = _s(m, S_TILE).get()
    ml = 1 + _s(m, S_TIER).get() + select(t == ELITE, 2, 0) + select(t == BOSS, 4, 0)
    _s(m, S_ML).set(ml + (_r(m, RDP).get() // NIGHT_EVERY) % 2)
    _s(m, S_COMBAT).set(select(t == MONSTER, 1, select(t == ELITE, 1, t == BOSS)))


def _stamina(m):
    """Regenerate, then price the reaction. An unaffordable reaction degrades to Default — it never
    reverts, because a revert would let a mistimed plan brick a run that the chain has already decided."""
    _r(m, RST).set(vmin(STAM_MAX, _r(m, RST).get() + 1))
    cost = park(m, S_T0, m.slot(TCOST, _s(m, S_ACT).get()).get())
    aff = park(m, S_T1, cost <= _r(m, RST).get())
    _s(m, S_ACT).set(select(aff, _s(m, S_ACT).get(), A_DEFAULT))
    _r(m, RST).set(csub(_r(m, RST).get(), cost * aff))


def _fight(m):
    """One engagement, MAMEC's shape: damage scales with the pull, renown scales with the pull AND with how
    hurt you already are, armour absorbs one swing's worth, the weapon feeds renown rather than damage, and
    a fight that did not hurt you heals you nothing."""
    st = _r(m, RSN).get()
    _s(m, S_DN).set(m.slot(TSDMG, st).get())
    _s(m, S_XN).set(m.slot(TSXP, st).get())
    _s(m, S_SG).set(m.slot(TSGAIN, st).get())
    _s(m, S_SCAP).set(m.slot(TSCAP, st).get())

    tile = _s(m, S_TILE).get()
    _s(m, S_FAM).set(_s(m, S_B).get() % 3)
    _s(m, S_FOES).set(select(tile == BOSS, 1, _s(m, S_AGG).get()))
    isboss = park(m, S_T1, _s(m, S_TILE).get() == BOSS)

    fam = _s(m, S_FAM).get()
    ml = _s(m, S_ML).get()
    _s(m, S_ATK).set(m.slot(TFA0, fam).get() + m.slot(TFA1, fam).get() * ml)
    _s(m, S_ATK).set(_s(m, S_ATK).get() + (_s(m, S_B).get() // 3) % 4)
    _s(m, S_T0).set(select(isboss, 4, 1))
    _s(m, S_ATK).set(_s(m, S_ATK).get() * _s(m, S_T0).get())
    _s(m, S_XPE).set(m.slot(TFX0, fam).get() + m.slot(TFX1, fam).get() * ml)
    _s(m, S_T0).set(select(isboss, 12, 1))
    _s(m, S_XPE).set(_s(m, S_XPE).get() * _s(m, S_T0).get())

    # ---- damage in: stance, reaction, +/-10% variance, then PER-ENGAGEMENT absorption ----------------
    act = _s(m, S_ACT).get()
    _s(m, S_ATK).set(_s(m, S_ATK).get() * _s(m, S_DN).get() // 4)
    _s(m, S_T0).set(select(act == A_STRIKE, 5, 4))
    _s(m, S_ATK).set(_s(m, S_ATK).get() * _s(m, S_T0).get() // 4)
    _s(m, S_T0).set(select(act == A_GUARD, 2, 4))
    _s(m, S_ATK).set(_s(m, S_ATK).get() * _s(m, S_T0).get() // 4)
    _s(m, S_ATK).set(_s(m, S_ATK).get() * (90 + _s(m, S_X).get() % 21) // 100)

    _armor_pts(m, S_ABS)
    _s(m, S_T0).set(_s(m, S_FOES).get() * _s(m, S_ATK).get())
    raw = park(m, S_T1, csub(_s(m, S_T0).get(), _s(m, S_ABS).get()))
    # a horde ALWAYS draws blood: at least 1 hp per foe, however armoured you are. Without this floor,
    # enough armour nullifies any pull and greed becomes free.
    _s(m, S_DMG).set(vmax(raw, _s(m, S_FOES).get()))

    # ---- renown out (bloodlust reads the hp you went IN with) ----------------------------------------
    _s(m, S_HPB).set(_r(m, RHP).get())
    _weapon_power(m, S_WP)
    _s(m, S_WP).set(_s(m, S_WP).get() * _r(m, RFO).get() // 100)

    foes = _s(m, S_FOES).get()
    _s(m, S_BASE).set(foes * _s(m, S_XPE).get())
    _s(m, S_BASE).set(_s(m, S_BASE).get() * (HORDE_DIV + _s(m, S_FOES).get()) // HORDE_DIV)
    _s(m, S_BASE).set(_s(m, S_BASE).get() * (8 + _s(m, S_WP).get()) // 8)
    _s(m, S_BASE).set(_s(m, S_BASE).get() + _s(m, S_WP).get() * _r(m, RKI).get() // 64)
    _s(m, S_BASE).set(_s(m, S_BASE).get() * _s(m, S_XN).get() // 4)
    _s(m, S_T0).set(select(act == A_STRIKE, 5, 4))
    _s(m, S_BASE).set(_s(m, S_BASE).get() * _s(m, S_T0).get() // 4)

    # bloodlust: x1 at full hp, x5 at death's door, read from the hp you went IN with
    _s(m, S_T0).set(csub(_r(m, RMX).get(), _s(m, S_HPB).get()))
    _s(m, S_T0).set(_r(m, RMX).get() + 4 * _s(m, S_T0).get())
    _s(m, S_GAIN).set(_s(m, S_BASE).get() * _s(m, S_T0).get() // _r(m, RMX).get())

    # greed streak: every fight since your last heal compounds the payout
    _s(m, S_STK).set(vmin(_s(m, S_SCAP).get(), _r(m, RSK).get()))
    _s(m, S_GAIN).set(_s(m, S_GAIN).get() * (STREAK_DIV + _s(m, S_STK).get()) // STREAK_DIV)
    _r(m, RSK).set(_r(m, RSK).get() + _s(m, S_SG).get())

    # drinking forfeits your offence: you eat the exchange and earn nothing from it
    _s(m, S_GAIN).set(_s(m, S_GAIN).get() * csub(1, act == A_POTION))
    _r(m, RKI).set(_r(m, RKI).get() + _s(m, S_FOES).get())
    _r(m, RXP).set(_r(m, RXP).get() + _s(m, S_GAIN).get())

    # ---- materials: MAMEC's 80%-per-foe drop, made deterministic -------------------------------------
    _s(m, S_DROPS).set((_s(m, S_FOES).get() * 4 + _s(m, S_Z).get() % 5) // 5)
    for f, field in enumerate((RM0, RM1, RM2)):
        _s(m, S_T0).set(_s(m, S_DROPS).get() * (_s(m, S_FAM).get() == f))
        _r(m, field).set(_r(m, field).get() + _s(m, S_T0).get())

    # ---- hp: regen + lifesteal - damage, then the easy-win clamp -------------------------------------
    _s(m, S_T0).set(vmin(_r(m, RMX).get() // REGEN_CAP_DIV, _r(m, RXP).get() // REGEN_DIV))
    _s(m, S_T0).set(_s(m, S_T0).get() + _s(m, S_WP).get() // LIFESTEAL_DIV)   # lifesteal keeps the streak
    _s(m, S_T0).set(_s(m, S_HPB).get() + _s(m, S_T0).get())
    _s(m, S_ATK).set(csub(_s(m, S_T0).get(), _s(m, S_DMG).get()))    # S_ATK is now the hp accumulator
    _s(m, S_T1).set(_s(m, S_Y).get() % 2)
    _s(m, S_ATK).set(csub(_s(m, S_ATK).get(), _s(m, S_T1).get()))
    # "easy win! no healing." — a fight that left you no worse off gives nothing back
    _s(m, S_T2).set(_s(m, S_HPB).get() <= _s(m, S_ATK).get())
    _s(m, S_T3).set(csub(_s(m, S_HPB).get(), _s(m, S_T1).get()))
    _s(m, S_ATK).set(select(_s(m, S_T2).get(), _s(m, S_T3).get(), _s(m, S_ATK).get()))
    _r(m, RHP).set(vmin(_r(m, RMX).get(), _s(m, S_ATK).get()))

    # ---- drop -----------------------------------------------------------------------------------------
    t = _s(m, S_TILE).get()
    _s(m, S_T0).set(select(t == BOSS, 1, select(t == ELITE, 1, _s(m, S_Z).get() % 4 == 0)))
    _s(m, S_T1).set(select(t == BOSS, 2, select(t == ELITE, 1, 0)))
    _s(m, S_T2).set((_s(m, S_B).get() + _s(m, S_Z).get()) % 64)
    _roll_item(m, _s(m, S_T2).get(), _s(m, S_T1).get())
    _s(m, S_ITEM).set(_s(m, S_ITEM).get() * _s(m, S_T0).get())   # 0 = no drop
    _take_item_if_any(m)

    # ---- boss: the CHECKPOINT --------------------------------------------------------------------------
    boss = park(m, S_T0, _s(m, S_TILE).get() == BOSS)
    _r(m, RBK).set(select(boss, _r(m, RXP).get(), _r(m, RBK).get()))
    _r(m, RMX).set(_r(m, RMX).get() + 10 * boss)
    _s(m, S_T1).set(_r(m, RPO).get() + boss)
    _r(m, RPO).set(vmin(POTION_CAP, _s(m, S_T1).get()))


def _noncombat(m):
    """Hazard, cache, relic, shrine and forge. Each is guarded by its own tile test rather than a branch:
    the arithmetic is cheap next to a hash, and a straight-line body keeps the allocator's job trivial."""
    t = _s(m, S_TILE).get()
    tier = _s(m, S_TIER).get()

    # hazard — chip damage, halved for Evasive, softened by a little armour
    took = 2 + 2 * tier + _s(m, S_Y).get() % 6
    took = select(_r(m, RSN).get() == ST_EVASIVE, took // 2, took)
    _s(m, S_T4).set(took)
    _armor_pts(m, S_T5)
    _s(m, S_T4).set(csub(_s(m, S_T4).get(), _s(m, S_T5).get() // 8))
    _s(m, S_T4).set(_s(m, S_T4).get() * (t == HAZARD))
    _r(m, RHP).set(csub(_r(m, RHP).get(), _s(m, S_T4).get()))

    # cache / relic — a drop, with the relic guaranteed high tier
    _s(m, S_T4).set(select(t == CACHE, 1, t == RELIC))
    _s(m, S_T5).set(select(t == RELIC, 3, 0))
    _roll_item(m, _s(m, S_C).get(), _s(m, S_T5).get())
    _s(m, S_ITEM).set(_s(m, S_ITEM).get() * _s(m, S_T4).get())
    _take_item_if_any(m)

    # shrine — heal, sometimes a potion, and it costs the streak like every other heal
    shrine = park(m, S_T4, _s(m, S_TILE).get() == SHRINE)
    _s(m, S_T5).set(_r(m, RHP).get() + (SHRINE_BASE + 4 * _s(m, S_TIER).get()) * shrine)
    _r(m, RHP).set(vmin(_r(m, RMX).get(), _s(m, S_T5).get()))
    _s(m, S_T5).set(_r(m, RPO).get() + (_s(m, S_Z).get() % 4 == 0) * shrine)
    _r(m, RPO).set(vmin(POTION_CAP, _s(m, S_T5).get()))
    _r(m, RSK).set(_r(m, RSK).get() * csub(1, shrine))

    # forge — auto-craft (weapon first if you are weapon-focused), then buy a potion with scrap. Crafting
    # is automatic for the same reason auto-equip is: an absent player must keep progressing.
    forge = park(m, S_T6, _s(m, S_TILE).get() == FORGE)
    _s(m, S_T0).set(_r(m, RWL).get() < LEVEL_CAP)
    _s(m, S_T1).set(_r(m, RM0).get() >= SHARPEN_COST[0])
    _s(m, S_T2).set(_r(m, RM2).get() >= SHARPEN_COST[2])
    _s(m, S_ITEM).set(_s(m, S_T0).get() * _s(m, S_T1).get() * _s(m, S_T2).get())      # can sharpen
    _s(m, S_T0).set(_r(m, RAL).get() < LEVEL_CAP)
    _s(m, S_T1).set(_r(m, RM0).get() >= REINFORCE_COST[0])
    _s(m, S_T2).set(_r(m, RM1).get() >= REINFORCE_COST[1])
    _s(m, S_SLOT).set(_s(m, S_T0).get() * _s(m, S_T1).get() * _s(m, S_T2).get())      # can reinforce

    _s(m, S_T3).set(_r(m, RFO).get() >= 50)
    _s(m, S_T3).set(vmax(_s(m, S_T3).get(), csub(1, _s(m, S_SLOT).get())))            # prefer the weapon?
    _s(m, S_DROPS).set(_s(m, S_ITEM).get() * _s(m, S_T3).get() * forge)               # do sharpen
    _s(m, S_T4).set(_s(m, S_SLOT).get() * csub(1, _s(m, S_DROPS).get()) * forge)      # do reinforce

    _r(m, RWL).set(_r(m, RWL).get() + _s(m, S_DROPS).get())
    _r(m, RAL).set(_r(m, RAL).get() + _s(m, S_T4).get())
    _s(m, S_T5).set(_s(m, S_DROPS).get() * SHARPEN_COST[0] + _s(m, S_T4).get() * REINFORCE_COST[0])
    _r(m, RM0).set(csub(_r(m, RM0).get(), _s(m, S_T5).get()))
    _r(m, RM1).set(csub(_r(m, RM1).get(), _s(m, S_T4).get() * REINFORCE_COST[1]))
    _r(m, RM2).set(csub(_r(m, RM2).get(), _s(m, S_DROPS).get() * SHARPEN_COST[2]))

    _s(m, S_T0).set(_r(m, RM0).get() >= POTION_PRICE)
    _s(m, S_T1).set(_r(m, RPO).get() < POTION_CAP)
    _s(m, S_T2).set(_s(m, S_T0).get() * _s(m, S_T1).get() * forge)
    _r(m, RM0).set(csub(_r(m, RM0).get(), _s(m, S_T2).get() * POTION_PRICE))
    _r(m, RPO).set(_r(m, RPO).get() + _s(m, S_T2).get())


def _step(m):
    """One tile. Mirrors tests/autogame_model.step() statement for statement."""
    _derive(m)

    # unpack this step's 3-bit reaction from the packed plan word, then consume it
    _s(m, S_ACT).set(_s(m, S_PW).get() % 8)
    _s(m, S_PW).set(_s(m, S_PW).get() // 8)

    _classify(m)
    _stamina(m)

    act = _s(m, S_ACT).get()
    _s(m, S_AGG).set(vmin(AGG_MAX, _s(m, S_AGG).get()))
    _s(m, S_AGG).set(vmax(1, _s(m, S_AGG).get()))

    # rally — the only heal that KEEPS the streak, and the highest-skill line in the game
    rally = park(m, S_T0, act == A_RALLY)
    _s(m, S_T1).set(_r(m, RHP).get() + (RALLY_BASE + _s(m, S_TIER).get()) * rally)
    _r(m, RHP).set(vmin(_r(m, RMX).get(), _s(m, S_T1).get()))
    _s(m, S_T1).set(_r(m, RST).get() + 2 * rally)
    _r(m, RST).set(vmin(STAM_MAX, _s(m, S_T1).get()))

    # rest — MAMEC's: buy hp with score, and break the streak
    rest = park(m, S_T0, act == A_REST)
    _s(m, S_T1).set(_r(m, RHP).get() + (8 + _r(m, RXP).get() // 32) * rest)
    _r(m, RHP).set(vmin(_r(m, RMX).get(), _s(m, S_T1).get()))
    _s(m, S_T1).set((4 + _r(m, RXP).get() // 20) * rest)
    _r(m, RXP).set(csub(_r(m, RXP).get(), _s(m, S_T1).get()))
    _r(m, RBK).set(vmin(_r(m, RBK).get(), _r(m, RXP).get()))     # cannot rest away more than you hold
    _r(m, RSK).set(_r(m, RSK).get() * csub(1, rest))

    # potion — the explicit drink; the standing order below is the same act on a different trigger
    _s(m, S_DN).set(act == A_POTION)
    m.jnz(csub(1, _s(m, S_DN).get()), "nopot")
    _drink(m)
    m.label("nopot")

    # The tile itself, unless the reaction forfeited it. Computed HERE rather than earlier because _drink
    # above reuses the shared S_T* scratch, and a flag parked before it would be clobbered by it.
    _s(m, S_XN).set(select(act == A_SPRINT, 1, act == A_DODGE))
    _s(m, S_XN).set(csub(1, _s(m, S_XN).get()))
    m.jnz(csub(1, _s(m, S_XN).get()), "skiptile")
    m.jnz(csub(1, _s(m, S_COMBAT).get()), "nofight")
    _fight(m)
    m.jmp("skiptile")
    m.label("nofight")
    _noncombat(m)
    m.label("skiptile")

    # standing order: auto-drink under the threshold. This is what keeps an absent player alive through a
    # bad leg — and under bloodlust, picking the threshold is the sharpest decision in the game.
    low = park(m, S_T0, _r(m, RHP).get() * 100 < _r(m, RMX).get() * _r(m, RHL).get())
    alive = park(m, S_T1, _r(m, RHP).get() > 0)
    have = park(m, S_T2, _r(m, RPO).get() > 0)
    _s(m, S_DN).set(low * alive * have)
    m.jnz(csub(1, _s(m, S_DN).get()), "noauto")
    _drink(m)
    m.label("noauto")

    # advance the road, then settle the run's fate
    _r(m, RDP).set(_r(m, RDP).get() + 1)
    _r(m, RAV).set(_r(m, RHP).get() > 0)
    _r(m, RDN).set(_r(m, RDP).get() >= CHAPTER)


# ── methods ──────────────────────────────────────────────────────────────────────────────────────
def build():
    _LBL[0] = 0                                   # deterministic label numbering across rebuilds
    c = zkpy.Contract()

    with c.method("constructor") as m:
        for i, v in enumerate(COST):
            m.slot(TCOST, i).set(m.const(v))
        for i, (dn, xn, sg, sc) in enumerate(STANCES):
            m.slot(TSDMG, i).set(m.const(dn))
            m.slot(TSXP, i).set(m.const(xn))
            m.slot(TSGAIN, i).set(m.const(sg))
            m.slot(TSCAP, i).set(m.const(sc))
        for i, (c0, c1) in enumerate(FAM_ATK):
            m.slot(TFA0, i).set(m.const(c0))
            m.slot(TFA1, i).set(m.const(c1))
        for i, (c0, c1) in enumerate(FAM_XP):
            m.slot(TFX0, i).set(m.const(c0))
            m.slot(TFX1, i).set(m.const(c1))
        for i, v in enumerate(DEF_DIV):
            m.slot(TDEFD, i).set(m.const(v))
        m.ret(m.const(1))

    with c.method("begin") as m:
        # begin(runId): claim a fresh id and set out. The first tile height is pinned START_GAP blocks in
        # the FUTURE, so the terrain you will walk cannot be steered by when you call this.
        m.require(m.arg(0) > 0)
        m.require(_r(m, RA).get() == 0)
        _r(m, RA).set(m.caller())
        _r(m, RLH).set(m.cursor() + START_GAP)
        _r(m, RNH).set(m.cursor() + START_GAP + LEG)
        _r(m, RHP).set(m.const(HP0))
        _r(m, RMX).set(m.const(HP0))
        _r(m, RST).set(m.const(STAM_MAX))
        _r(m, RPO).set(m.const(POTIONS0))
        _r(m, RSN).set(m.const(ST_BALANCED))
        _r(m, RHL).set(m.const(35))
        _r(m, RFO).set(m.const(50))
        _r(m, RWL).set(m.const(1))
        _r(m, RAL).set(m.const(1))
        _r(m, RAV).set(m.const(1))
        m.slot(OWNRUN, m.caller()).set(m.arg(0))
        cnt = m.slot(RLIST, 0)                       # append to the enumerable run index
        m.slot(RLIST, cnt.get() + 1).set(m.arg(0))
        cnt.set(cnt.get() + 1)
        m.ret(m.arg(0))

    with c.method("stance") as m:                    # stance(runId, s)
        _own_or_die(m)
        _live(m)
        m.require(m.arg(1) < 4)
        _r(m, RSN).set(m.arg(1))
        m.ret(m.arg(1))

    with c.method("focus") as m:                     # focus(runId, f) — 100 = all weapon, 0 = all armour
        _own_or_die(m)
        _live(m)
        m.require(m.arg(1) <= 100)
        _r(m, RFO).set(m.arg(1))
        m.ret(m.arg(1))

    with c.method("orders") as m:                    # orders(runId, healPct)
        _own_or_die(m)
        _live(m)
        m.require(m.arg(1) <= 100)
        _r(m, RHL).set(m.arg(1))
        m.ret(m.arg(1))

    with c.method("plan") as m:
        # plan(runId, leg, word, agg): the reactions for one leg, plus its aggression dial. Only accepted
        # for the PENDING leg and only while its resolving hash does not exist yet — that is the whole
        # fairness argument, so both checks are hard requires.
        _own_or_die(m)
        _live(m)
        m.require(m.arg(1) == _r(m, RLG).get())
        m.require(m.cursor() < _r(m, RNH).get())
        m.require(m.arg(2) < (1 << 48))              # 16 actions x 3 bits
        m.require(m.arg(3) >= 1)
        m.require(m.arg(3) <= AGG_MAX)
        m.at(zhash(m.const(PLAN_TAG), m.arg(0), m.arg(1))).set(m.arg(2))
        m.at(zhash(m.const(AGG_TAG), m.arg(0), m.arg(1))).set(m.arg(3))
        m.ret(m.arg(1))

    with c.method("retire") as m:
        # retire(runId): walk away on your feet. Keeps everything, and earns the road bonus pro-rata on the
        # depth reached — the cash-out side of the push-or-bank decision.
        _own_or_die(m)
        _live(m)
        _r(m, RRT).set(m.const(1))
        m.ret(_r(m, RDP).get())

    with c.method("advance") as m:
        # advance(runId): resolve every leg whose rolling hash now exists, up to MAX_LEGS_PER_CALL.
        # PERMISSIONLESS — the outcome is a pure function of two already-final hashes, so who calls it and
        # when cannot change a single step.
        m.require(_r(m, RA).get() != 0)
        m.require(_r(m, RAV).get() == 1)
        m.require(_r(m, RDN).get() == 0)
        m.require(_r(m, RRT).get() == 0)
        _s(m, S_LEGS).set(m.const(0))

        m.label("leg")
        m.jnz(m.cursor() < _r(m, RNH).get(), "done")            # the rolls do not exist yet
        m.jnz(_s(m, S_LEGS).get() >= MAX_LEGS_PER_CALL, "done")

        _s(m, S_T).set(m.bhash(_r(m, RLH).get()))               # tiles: pinned, already visible
        _s(m, S_R).set(m.bhash(_r(m, RNH).get()))               # rolls: unknowable while planning
        _s(m, S_PW).set(m.at(zhash(m.const(PLAN_TAG), m.arg(0), _r(m, RLG).get())).get())
        _s(m, S_AGG).set(vmax(1, m.at(zhash(m.const(AGG_TAG), m.arg(0), _r(m, RLG).get())).get()))
        _s(m, S_I).set(m.const(0))

        m.label("step")
        m.jnz(_s(m, S_I).get() >= LEG, "legdone")
        _step(m)
        _s(m, S_I).set(_s(m, S_I).get() + 1)
        m.jnz(_r(m, RAV).get() == 0, "legdone")                 # died mid-leg: stop where you fell
        m.jnz(_r(m, RDN).get(), "legdone")
        m.jmp("step")

        m.label("legdone")
        _r(m, RLH).set(_r(m, RNH).get())                        # slide the window one leg forward
        _r(m, RNH).set(_r(m, RNH).get() + LEG)
        _r(m, RLG).set(_r(m, RLG).get() + 1)
        _s(m, S_LEGS).set(_s(m, S_LEGS).get() + 1)
        m.jnz(_r(m, RAV).get() == 0, "done")
        m.jnz(_r(m, RDN).get(), "done")
        m.jmp("leg")

        m.label("done")
        for i in range(NSCRATCH):                               # clear scratch: no residue in the state root
            _s(m, i).set(m.const(0))
        m.ret(_r(m, RDP).get())

    return c.build()


ABI = {
    "constructor": {"args": []},
    "begin": {"args": ["runId"]},
    "stance": {"args": ["runId", "stance"]},
    "focus": {"args": ["runId", "focus"]},
    "orders": {"args": ["runId", "healPct"]},
    "plan": {"args": ["runId", "leg", "word", "agg"]},
    "retire": {"args": ["runId"]},
    "advance": {"args": ["runId"]},
    "_view": {
        "index": {"cnt": 0, "list": RLIST, "name": "runs"},
        "maps": {
            "ra": RA, "lh": RLH, "nh": RNH, "hp": RHP, "mx": RMX, "st": RST, "po": RPO, "xp": RXP,
            "bk": RBK, "dp": RDP, "ki": RKI, "sn": RSN, "hl": RHL, "fo": RFO, "wl": RWL, "al": RAL,
            "m0": RM0, "m1": RM1, "m2": RM2, "av": RAV, "dn": RDN, "rt": RRT, "lg": RLG, "sk": RSK,
            "g0": GEAR0, "g1": GEAR0 + 1, "g2": GEAR0 + 2, "g3": GEAR0 + 3, "g4": GEAR0 + 4,
            "g5": GEAR0 + 5,
        },
        "addr": ["ra"],
    },
}
