#!/usr/bin/env python3
"""
Inlines every per-game translation JSON in this directory into the T_GAMES block of ../i18n.js.

The shared runtime (static/i18n.js) does NOT fetch these JSONs at runtime — it carries a generated
`const T_GAMES = {…}` block (between the `>>> GAMES i18n` / `<<< GAMES i18n` markers) that it merges
into its language tables on load. So after editing any static/i18n_games/<game>.json you MUST re-run
this script and commit the regenerated i18n.js, or the changes never reach the browser.

Each <game>.json is {lang: {key: text}} across all 16 languages. Games keep their own key prefix
(farkle uses bare keys, tictactoe `ttt.`, gameslobby `games.`, roulette `roul.`, the rest `<game>.`);
keys are asserted collision-free across games before writing.

Run: python3 static/i18n_games/merge_games.py
"""
import json, os, sys, glob

HERE = os.path.dirname(os.path.abspath(__file__))
I18N = os.path.join(HERE, "..", "i18n.js")
LANGS = ["en","cs","es","pt","fr","de","it","ru","zh","ja","ko","ar","hi","tr","id","vi"]
# Deterministic merge order; farkle/slots/tictactoe first to match the historical block.
ORDER = ["farkle","slots","tictactoe","bet","chess","coinflip","dice","gameslobby","roulette","poker"]

def main():
    files = sorted(glob.glob(os.path.join(HERE, "*.json")))
    games = [os.path.splitext(os.path.basename(f))[0] for f in files]
    games = [g for g in ORDER if g in games] + [g for g in games if g not in ORDER]
    data = {g: json.load(open(os.path.join(HERE, g + ".json"), encoding="utf-8")) for g in games}

    # Every game must define all 16 languages with identical key sets to its own `en`.
    for g in games:
        enk = set(data[g]["en"])
        for l in LANGS:
            if l not in data[g]:
                sys.exit(f"{g}.json: missing language {l!r}")
            if set(data[g][l]) != enk:
                sys.exit(f"{g}.json: language {l!r} key set differs from en")

    # Cross-game collision guard.
    seen = {}
    for g in games:
        for k in data[g]["en"]:
            if k in seen:
                sys.exit(f"key collision {k!r} between {seen[k]} and {g}")
            seen[k] = g

    lines = ["  // >>> GAMES i18n (generated by merge_games.py — do not edit between the markers)",
             "  const T_GAMES = {"]
    for l in LANGS:
        merged = {}
        for g in games:
            merged.update(data[g][l])
        lines.append(f"    {l}: " + json.dumps(merged, ensure_ascii=False) + ",")
    lines.append("  };")
    lines.append("  for (const l in T_GAMES) { T[l] = T[l] || {}; Object.assign(T[l], T_GAMES[l]); }")
    lines.append("  // <<< GAMES i18n")
    block = "\n".join(lines)

    src = open(I18N, encoding="utf-8").read()
    start = src.index("  // >>> GAMES i18n")
    end = src.index("  // <<< GAMES i18n") + len("  // <<< GAMES i18n")
    src = src[:start] + block + src[end:]
    open(I18N, "w", encoding="utf-8").write(src)
    print(f"inlined {len(games)} games ({', '.join(games)}) x {len(LANGS)} langs into i18n.js")


def bust_pages():
    """Stamp every static/*.html i18n.js reference with a content hash — Cloudflare caches /static js,
    so without this the freshly merged bundle never reaches visitors (the 'translations missing' bug)."""
    import hashlib, re as _re
    h = hashlib.md5(open(I18N, "rb").read()).hexdigest()[:8]
    for page in glob.glob(os.path.join(HERE, "..", "*.html")):
        src = open(page, encoding="utf-8").read()
        out = _re.sub(r'src="/static/i18n\.js[^"]*"', 'src="/static/i18n.js?v=%s"' % h, src)
        if out != src:
            open(page, "w", encoding="utf-8").write(out)
    print("stamped i18n.js?v=%s into game pages" % h)

if __name__ == "__main__":
    main()
    bust_pages()
