#!/usr/bin/env python3
"""
Builds static/i18n.js — the WHOLE file — from its sources. Nothing in i18n.js is edited by hand any more.

  static/i18n/runtime.js.tmpl     the runtime (window.t, the picker, applyI18n …) with an @@TABLES@@ slot
  static/i18n/<namespace>.json    the wallet / site strings, one file per key prefix (misc.json for small ones)
  static/i18n_games/<game>.json   the per-game strings (also written by _gen_chess.py / _gen_hexholm.py)

Every source file is {lang: {key: text}} across exactly the 16 languages below. A key is DEFINED ONCE, in one file.

WHY (2026-10-10). i18n.js was layered: a base table, 110 hand-appended patch tables merged with Object.assign, the
generated games block and a hand-written site block. 129 keys were defined more than once and the last definition won
silently — an edit to the first one changed nothing on screen, and "the literal appears 16 times" stopped meaning "16
languages define it" (tests/test_device_attest_hw.py). People added keys by regex-inserting into a 7 MB file. Now a
key lives in one JSON file and this script refuses, before writing anything:
  * a key defined in two files (the layering bug, made impossible);
  * a file whose languages do not carry the same key set as its `en` (a language silently falling back to English);
  * a {placeholder} set in any language that differs from `en` (a literal "{t}" rendered to the user);
  * an empty or non-string text (t() treats "" as missing and shows the English fallback);
  * a language set other than the 16 below, or a runtime NAMES table that disagrees with it.

Usage:
  python3 tools/build_i18n.py           # regenerate static/i18n.js
  python3 tools/build_i18n.py --check   # exit 1 when the committed i18n.js is not exactly what the sources build
                                        # (tests/i18n_coverage.mjs runs this)
Adding a string: put the key into the namespace file of its prefix (static/i18n/<prefix>.json, or misc.json when
there is none) in ALL 16 languages, then run this script and commit the JSON together with the regenerated i18n.js.
static/i18n_games/merge_games.py is kept as the old entry point and runs this.
"""
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC = os.path.join(ROOT, "static")
NS_DIR = os.path.join(STATIC, "i18n")
GAMES_DIR = os.path.join(STATIC, "i18n_games")
TEMPLATE = os.path.join(NS_DIR, "runtime.js.tmpl")
OUT = os.path.join(STATIC, "i18n.js")

LANGS = ["en", "cs", "es", "pt", "fr", "de", "it", "ru", "zh", "ja", "ko", "ar", "hi", "tr", "id", "vi"]
# Deterministic games order; farkle/slots/tictactoe first to match the historical T_GAMES block.
GAMES_ORDER = ["farkle", "slots", "tictactoe", "bet", "chess", "coinflip", "dice", "gameslobby", "roulette", "poker"]
# Same pattern tests/i18n_coverage.mjs uses for the code's own defaults.
PLACEHOLDER = re.compile(r"\{([A-Za-z_]\w*)\}")
GENERATED_NOTE = ("GENERATED by tools/build_i18n.py — DO NOT EDIT. Strings live in static/i18n/*.json and\n"
                  " * static/i18n_games/*.json (one definition per key, all 16 languages); the runtime lives in\n"
                  " * static/i18n/runtime.js.tmpl. Edit those, run `python3 tools/build_i18n.py`, commit both.")


class I18nError(Exception):
    pass


def source_files():
    """Namespace files (sorted) then game files (GAMES_ORDER first, then sorted) — the order keys are emitted in."""
    ns = sorted(glob.glob(os.path.join(NS_DIR, "*.json")))
    games = sorted(glob.glob(os.path.join(GAMES_DIR, "*.json")))
    names = [os.path.splitext(os.path.basename(f))[0] for f in games]
    order = [g for g in GAMES_ORDER if g in names] + [g for g in names if g not in GAMES_ORDER]
    return ns + [os.path.join(GAMES_DIR, g + ".json") for g in order]


def load_and_validate(files=None):
    """{lang: [(key, text), ...]} in emission order, after every refusal rule has passed. Raises I18nError listing
    EVERY problem found (not just the first), so one run tells the author everything to fix."""
    files = source_files() if files is None else files
    errs = []
    owner = {}
    tables = {l: [] for l in LANGS}
    for path in files:
        rel = os.path.relpath(path, ROOT)
        try:
            data = json.load(open(path, encoding="utf-8"))
        except (OSError, ValueError) as e:
            errs.append(f"{rel}: not readable JSON ({e})")
            continue
        if not isinstance(data, dict):
            errs.append(f"{rel}: top level must be {{lang: {{key: text}}}}")
            continue
        missing = [l for l in LANGS if l not in data]
        extra = [l for l in data if l not in LANGS]
        if missing or extra:
            errs.append(f"{rel}: languages must be exactly {','.join(LANGS)} (missing {missing}, unknown {extra})")
            continue
        en = data["en"]
        if not isinstance(en, dict) or not en:
            errs.append(f"{rel}: `en` must be a non-empty object")
            continue
        enk = set(en)
        for l in LANGS:
            if not isinstance(data[l], dict):
                errs.append(f"{rel}: {l} is not an object")
                continue
            got = set(data[l])
            if got != enk:
                errs.append(f"{rel}: {l} key set drifts from en — missing {sorted(enk - got)[:8]}, "
                            f"extra {sorted(got - enk)[:8]}")
        for k in en:
            if k in owner:
                errs.append(f"duplicate key {k!r}: defined in {owner[k]} and {rel} (define it once)")
            else:
                owner[k] = rel
            if not isinstance(k, str) or not k.strip():
                errs.append(f"{rel}: empty key")
            want = sorted(set(PLACEHOLDER.findall(en[k]))) if isinstance(en[k], str) else None
            for l in LANGS:
                v = data[l].get(k) if isinstance(data[l], dict) else None
                if k not in data[l]:
                    continue            # reported above as drift
                if not isinstance(v, str) or v == "":
                    errs.append(f"{rel}: {k} [{l}] is empty or not a string")
                    continue
                if want is not None and sorted(set(PLACEHOLDER.findall(v))) != want:
                    errs.append(f"{rel}: {k} [{l}] placeholders {{{','.join(sorted(set(PLACEHOLDER.findall(v))))}}}"
                                f" differ from en {{{','.join(want)}}}")
        for l in LANGS:
            if isinstance(data[l], dict):
                tables[l].extend((k, data[l][k]) for k in en if k in data[l])
    if errs:
        raise I18nError("\n".join(errs))
    return tables


def check_template(tmpl):
    if tmpl.count("@@TABLES@@") != 1 or tmpl.count("@@GENERATED@@") != 1:
        raise I18nError(f"{os.path.relpath(TEMPLATE, ROOT)}: needs exactly one @@TABLES@@ and one @@GENERATED@@")
    m = re.search(r"const NAMES = \{([^}]*)\}", tmpl)
    names = re.findall(r"\b([a-z]{2})\s*:", m.group(1)) if m else []
    if names != LANGS:
        raise I18nError(f"runtime NAMES {names} must list exactly the 16 languages in order {LANGS}")


def render(tables, tmpl):
    """The whole i18n.js text. One key per line, so a diff of the generated file reads as the strings that changed."""
    parts = []
    for i, l in enumerate(LANGS):
        body = ",\n".join("      " + json.dumps(k, ensure_ascii=False) + ": " + json.dumps(v, ensure_ascii=False)
                          for k, v in tables[l])
        parts.append(f"    {l}: {{\n{body}\n    }}" + ("," if i < len(LANGS) - 1 else ""))
    return tmpl.replace("@@GENERATED@@", GENERATED_NOTE).replace("@@TABLES@@", "\n".join(parts))


def build():
    tmpl = open(TEMPLATE, encoding="utf-8").read()
    check_template(tmpl)
    return render(load_and_validate(), tmpl)


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    try:
        text = build()
    except I18nError as e:
        print("build_i18n: REFUSED\n" + str(e), file=sys.stderr)
        return 2
    if "--check" in argv:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if cur != text:
            print("build_i18n: static/i18n.js is NOT the generator's output — edit the JSON sources, never i18n.js, "
                  "and run `python3 tools/build_i18n.py`", file=sys.stderr)
            return 1
        print(f"build_i18n: static/i18n.js is current ({len(text.encode())} bytes)")
        return 0
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    n = text.count("\n      \"") // len(LANGS)
    print(f"build_i18n: wrote static/i18n.js — {len(LANGS)} languages x {n} keys, {len(text.encode())} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
